/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PhongKham.ui;

import PhongKham.entity.NhanVienPK;

import java.awt.CardLayout;
import PhongKham.ui.ChaoGD;
import PhongKham.utils.Auth;
import static PhongKham.utils.Auth.user;
import PhongKham.utils.XImage;
import PhongKham.utils.MsgBox;
import java.awt.Desktop;
import java.awt.event.ActionEvent;
import java.io.File;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.Timer;
import PhongKham.utils.XJdbc;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Admin
 */
public class ClinicPK extends javax.swing.JFrame {

	/**
	 * Creates new form ClinicPK
	 */
	public CardLayout card = new CardLayout();

	public ClinicPK() {
		initComponents();
		chuChay();
		init();
		this.setLocationRelativeTo(null);
//        TrangChuJPan.setLayout(card);
		DoiMatKhauJPan.setLayout(card);
		TaoTaiKhoanJPan.setLayout(card);
		DangXuatJPan.setLayout(card);
		TiepNhanBNJPan.setLayout(card);
		KhamBenhJPan.setLayout(card);
		NhanVienJPan.setLayout(card);
		BenhNhanJPan.setLayout(card);
		LichKhamJPan.setLayout(card);
		ThuocJPan.setLayout(card);
		BenhNhanJPan.setLayout(card);
		ThietBiJPan.setLayout(card);
		PhongJPan.setLayout(card);
		HoaDonThuocJPan.setLayout(card);
		ThuVienPhiJPan.setLayout(card);
		ThongKeNVJPan.setLayout(card);
		ThongKeBNJPan.setLayout(card);
		ThongKeTJPan.setLayout(card);
		ThongKeTBJPan.setLayout(card);
		ThongKeDVJPan.setLayout(card);
		ThongKeDTJPan.setLayout(card);
		HuongDanJPan.setLayout(card);
		GioiThieuJPan.setLayout(card);
		DichVuJPan.setLayout(card);
//        QLDichVuJPan.setLayout(card);

	}

	public void chuChay() {
		Thread thread1 = new Thread() {
			@Override
			public void run() {
				String txt = lblChuChay.getText() + " ";
				while (true) {
					txt = txt.substring(1, txt.length()) + txt.charAt(0);
//                    txt = txt.charAt(txt.length()-1)+ txt.substring(0,txt.length()-1);
					try {
						sleep(500);
					} catch (InterruptedException ex) {
						Logger.getLogger(ClinicPK.class.getName()).log(Level.SEVERE, null, ex);
					}
					lblChuChay.setText(txt);
				}
			}

		};
		thread1.start();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		Menu = new javax.swing.JTabbedPane();
		HeThong = new javax.swing.JPanel();
		jPanel3 = new javax.swing.JPanel();
		btnDoiMatKhau = new javax.swing.JButton();
		btnTTK = new javax.swing.JButton();
		btnDangXuat = new javax.swing.JButton();
		btnThoat = new javax.swing.JButton();
		lblChuChay = new javax.swing.JLabel();
		cha = new javax.swing.JPanel();
		TrangChu = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		DoiMatKhauJPan = new javax.swing.JPanel();
		TaoTaiKhoanJPan = new javax.swing.JPanel();
		DangXuatJPan = new javax.swing.JPanel();
		QuanLy = new javax.swing.JPanel();
		jPanel1 = new javax.swing.JPanel();
		btnTiepNhan = new javax.swing.JButton();
		btnKhamBenh = new javax.swing.JButton();
		btnNhanVien = new javax.swing.JButton();
		btnBenhNhan = new javax.swing.JButton();
		btnLichKham = new javax.swing.JButton();
		btnThuoc = new javax.swing.JButton();
		btnThietBi = new javax.swing.JButton();
		btnPhong = new javax.swing.JButton();
		btnHoaDonThuoc = new javax.swing.JButton();
		btnThuVienPhi = new javax.swing.JButton();
		jSeparator1 = new javax.swing.JSeparator();
		jSeparator2 = new javax.swing.JSeparator();
		jSeparator3 = new javax.swing.JSeparator();
		parentpanel = new javax.swing.JPanel();
		TrangChu2 = new javax.swing.JPanel();
		jLabel3 = new javax.swing.JLabel();
		TiepNhanBNJPan = new javax.swing.JPanel();
		KhamBenhJPan = new javax.swing.JPanel();
		NhanVienJPan = new javax.swing.JPanel();
		BenhNhanJPan = new javax.swing.JPanel();
		LichKhamJPan = new javax.swing.JPanel();
		ThuocJPan = new javax.swing.JPanel();
		ThietBiJPan = new javax.swing.JPanel();
		PhongJPan = new javax.swing.JPanel();
		HoaDonThuocJPan = new javax.swing.JPanel();
		ThuVienPhiJPan = new javax.swing.JPanel();
		ThongKe = new javax.swing.JPanel();
		jPanel4 = new javax.swing.JPanel();
		btnThongKeNV = new javax.swing.JButton();
		btnThongKeBN = new javax.swing.JButton();
		btnThongKeThuoc = new javax.swing.JButton();
		btnThongKeThietBi = new javax.swing.JButton();
		btnThongKeDichVu = new javax.swing.JButton();
		btnThongKeDT = new javax.swing.JButton();
		jSeparator4 = new javax.swing.JSeparator();
		jSeparator5 = new javax.swing.JSeparator();
		jSeparator6 = new javax.swing.JSeparator();
		jSeparator7 = new javax.swing.JSeparator();
		jSeparator8 = new javax.swing.JSeparator();
		boo = new javax.swing.JPanel();
		TrangChu1 = new javax.swing.JPanel();
		jLabel2 = new javax.swing.JLabel();
		ThongKeNVJPan = new javax.swing.JPanel();
		ThongKeBNJPan = new javax.swing.JPanel();
		ThongKeTJPan = new javax.swing.JPanel();
		ThongKeTBJPan = new javax.swing.JPanel();
		ThongKeDVJPan = new javax.swing.JPanel();
		ThongKeDTJPan = new javax.swing.JPanel();
		TroGiup = new javax.swing.JPanel();
		jPanel2 = new javax.swing.JPanel();
		btnHuongDan = new javax.swing.JButton();
		btnGioiThieu = new javax.swing.JButton();
		btnDichVu = new javax.swing.JButton();
		bo = new javax.swing.JPanel();
		TrangChu3 = new javax.swing.JPanel();
		jLabel4 = new javax.swing.JLabel();
		HuongDanJPan = new javax.swing.JPanel();
		GioiThieuJPan = new javax.swing.JPanel();
		DichVuJPan = new javax.swing.JPanel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("Clinic");

		Menu.setBackground(new java.awt.Color(204, 204, 204));
		Menu.setFocusable(false);
		Menu.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
		Menu.setMinimumSize(new java.awt.Dimension(53, 108));
		Menu.setPreferredSize(new java.awt.Dimension(1500, 825));

		HeThong.setBackground(new java.awt.Color(204, 255, 204));
		HeThong.setLayout(new java.awt.BorderLayout());

		jPanel3.setBackground(new java.awt.Color(0, 204, 255));
		jPanel3.setPreferredSize(new java.awt.Dimension(942, 70));

		btnDoiMatKhau.setBackground(new java.awt.Color(0, 204, 255));
		btnDoiMatKhau.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
		btnDoiMatKhau.setForeground(new java.awt.Color(255, 255, 153));
		btnDoiMatKhau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PhongKham/Hinh/padlock.png"))); // NOI18N
		btnDoiMatKhau.setText("Đổi Mật Khẩu");
		btnDoiMatKhau.setBorder(null);
		btnDoiMatKhau.setFocusable(false);
		btnDoiMatKhau.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnDoiMatKhauActionPerformed(evt);
			}
		});

		btnTTK.setBackground(new java.awt.Color(0, 204, 255));
		btnTTK.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
		btnTTK.setForeground(new java.awt.Color(255, 255, 153));
		btnTTK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PhongKham/Hinh/add-user.png"))); // NOI18N
		btnTTK.setText("Tạo Tài Khoản");
		btnTTK.setBorder(null);
		btnTTK.setFocusable(false);
		btnTTK.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnTTKActionPerformed(evt);
			}
		});

		btnDangXuat.setBackground(new java.awt.Color(0, 204, 255));
		btnDangXuat.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
		btnDangXuat.setForeground(new java.awt.Color(255, 255, 153));
		btnDangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PhongKham/Hinh/exit.png"))); // NOI18N
		btnDangXuat.setText("Đăng Xuất");
		btnDangXuat.setBorder(null);
		btnDangXuat.setFocusable(false);
		btnDangXuat.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnDangXuatActionPerformed(evt);
			}
		});

		btnThoat.setBackground(new java.awt.Color(0, 204, 255));
		btnThoat.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
		btnThoat.setForeground(new java.awt.Color(255, 255, 153));
		btnThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PhongKham/Hinh/logout.png"))); // NOI18N
		btnThoat.setText("Thoát");
		btnThoat.setBorder(null);
		btnThoat.setFocusable(false);
		btnThoat.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnThoatActionPerformed(evt);
			}
		});

		lblChuChay.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
		lblChuChay.setForeground(new java.awt.Color(255, 255, 102));
		lblChuChay.setText("Clinic FPT - Phòng Khám Y Tế Hàng Đầu ");

		javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
		jPanel3.setLayout(jPanel3Layout);
		jPanel3Layout.setHorizontalGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel3Layout.createSequentialGroup().addContainerGap().addComponent(btnDoiMatKhau)
						.addGap(18, 18, 18).addComponent(btnTTK).addGap(18, 18, 18).addComponent(btnDangXuat)
						.addGap(18, 18, 18)
						.addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 110,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(216, 216, 216).addComponent(lblChuChay).addContainerGap(120, Short.MAX_VALUE)));
		jPanel3Layout.setVerticalGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel3Layout.createSequentialGroup().addContainerGap().addGroup(jPanel3Layout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
						.addComponent(lblChuChay, javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout
								.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(btnDoiMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 40,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(btnTTK, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
								.addComponent(btnDangXuat).addComponent(btnThoat,
										javax.swing.GroupLayout.PREFERRED_SIZE, 40,
										javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addContainerGap(17, Short.MAX_VALUE)));

		HeThong.add(jPanel3, java.awt.BorderLayout.PAGE_START);

		cha.setBackground(new java.awt.Color(204, 255, 204));
		cha.setLayout(new java.awt.CardLayout());

		TrangChu.setBackground(new java.awt.Color(51, 255, 51));
		TrangChu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
		TrangChu.setPreferredSize(new java.awt.Dimension(1600, 850));

		jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PhongKham/Hinh/TrangChu.png"))); // NOI18N
		jLabel1.setPreferredSize(new java.awt.Dimension(1600, 850));

		javax.swing.GroupLayout TrangChuLayout = new javax.swing.GroupLayout(TrangChu);
		TrangChu.setLayout(TrangChuLayout);
		TrangChuLayout.setHorizontalGroup(TrangChuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
						TrangChuLayout.createSequentialGroup()
								.addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1655, Short.MAX_VALUE)
								.addContainerGap()));
		TrangChuLayout.setVerticalGroup(TrangChuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 721, Short.MAX_VALUE));

		cha.add(TrangChu, "card3");

		DoiMatKhauJPan.setPreferredSize(new java.awt.Dimension(500, 300));

		javax.swing.GroupLayout DoiMatKhauJPanLayout = new javax.swing.GroupLayout(DoiMatKhauJPan);
		DoiMatKhauJPan.setLayout(DoiMatKhauJPanLayout);
		DoiMatKhauJPanLayout.setHorizontalGroup(DoiMatKhauJPanLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 1523, Short.MAX_VALUE));
		DoiMatKhauJPanLayout.setVerticalGroup(DoiMatKhauJPanLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 721, Short.MAX_VALUE));

		cha.add(DoiMatKhauJPan, "card3");

		javax.swing.GroupLayout TaoTaiKhoanJPanLayout = new javax.swing.GroupLayout(TaoTaiKhoanJPan);
		TaoTaiKhoanJPan.setLayout(TaoTaiKhoanJPanLayout);
		TaoTaiKhoanJPanLayout.setHorizontalGroup(TaoTaiKhoanJPanLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 1523, Short.MAX_VALUE));
		TaoTaiKhoanJPanLayout.setVerticalGroup(TaoTaiKhoanJPanLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 721, Short.MAX_VALUE));

		cha.add(TaoTaiKhoanJPan, "card4");

		javax.swing.GroupLayout DangXuatJPanLayout = new javax.swing.GroupLayout(DangXuatJPan);
		DangXuatJPan.setLayout(DangXuatJPanLayout);
		DangXuatJPanLayout.setHorizontalGroup(DangXuatJPanLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 1523, Short.MAX_VALUE));
		DangXuatJPanLayout.setVerticalGroup(DangXuatJPanLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 721, Short.MAX_VALUE));

		cha.add(DangXuatJPan, "card5");

		HeThong.add(cha, java.awt.BorderLayout.CENTER);

		Menu.addTab("Hệ Thống", HeThong);

		QuanLy.setPreferredSize(new java.awt.Dimension(1645, 730));
		QuanLy.setLayout(new java.awt.BorderLayout());

		jPanel1.setBackground(new java.awt.Color(0, 204, 255));
		jPanel1.setPreferredSize(new java.awt.Dimension(942, 70));

		btnTiepNhan.setBackground(new java.awt.Color(0, 204, 255));
		btnTiepNhan.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
		btnTiepNhan.setForeground(new java.awt.Color(255, 255, 153));
		btnTiepNhan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PhongKham/Hinh/doctor-visit.png"))); // NOI18N
		btnTiepNhan.setText("Tiếp Nhận ");
		btnTiepNhan.setBorder(null);
		btnTiepNhan.setFocusable(false);
		btnTiepNhan.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnTiepNhanActionPerformed(evt);
			}
		});

		btnKhamBenh.setBackground(new java.awt.Color(0, 204, 255));
		btnKhamBenh.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
		btnKhamBenh.setForeground(new java.awt.Color(255, 255, 153));
		btnKhamBenh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PhongKham/Hinh/examination.png"))); // NOI18N
		btnKhamBenh.setText("Khám Bệnh");
		btnKhamBenh.setBorder(null);
		btnKhamBenh.setFocusable(false);
		btnKhamBenh.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnKhamBenhActionPerformed(evt);
			}
		});

		btnNhanVien.setBackground(new java.awt.Color(0, 204, 255));
		btnNhanVien.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
		btnNhanVien.setForeground(new java.awt.Color(255, 255, 153));
		btnNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PhongKham/Hinh/medical-team.png"))); // NOI18N
		btnNhanVien.setText("Nhân Viên");
		btnNhanVien.setBorder(null);
		btnNhanVien.setFocusable(false);
		btnNhanVien.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnNhanVienActionPerformed(evt);
			}
		});

		btnBenhNhan.setBackground(new java.awt.Color(0, 204, 255));
		btnBenhNhan.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
		btnBenhNhan.setForeground(new java.awt.Color(255, 255, 153));
		btnBenhNhan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PhongKham/Hinh/hospitalisation.png"))); // NOI18N
		btnBenhNhan.setText("Bệnh Nhân");
		btnBenhNhan.setBorder(null);
		btnBenhNhan.setFocusable(false);
		btnBenhNhan.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnBenhNhanActionPerformed(evt);
			}
		});

		btnLichKham.setBackground(new java.awt.Color(0, 204, 255));
		btnLichKham.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
		btnLichKham.setForeground(new java.awt.Color(255, 255, 153));
		btnLichKham.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PhongKham/Hinh/clipboard.png"))); // NOI18N
		btnLichKham.setText("Lịch Khám");
		btnLichKham.setBorder(null);
		btnLichKham.setFocusable(false);
		btnLichKham.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnLichKhamActionPerformed(evt);
			}
		});

		btnThuoc.setBackground(new java.awt.Color(0, 204, 255));
		btnThuoc.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
		btnThuoc.setForeground(new java.awt.Color(255, 255, 153));
		btnThuoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PhongKham/Hinh/pills.png"))); // NOI18N
		btnThuoc.setText(" Thuốc");
		btnThuoc.setBorder(null);
		btnThuoc.setFocusable(false);
		btnThuoc.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnThuocActionPerformed(evt);
			}
		});

		btnThietBi.setBackground(new java.awt.Color(0, 204, 255));
		btnThietBi.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
		btnThietBi.setForeground(new java.awt.Color(255, 255, 153));
		btnThietBi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PhongKham/Hinh/measuring-device.png"))); // NOI18N
		btnThietBi.setText(" Thiêt Bị");
		btnThietBi.setBorder(null);
		btnThietBi.setFocusable(false);
		btnThietBi.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnThietBiActionPerformed(evt);
			}
		});

		btnPhong.setBackground(new java.awt.Color(0, 204, 255));
		btnPhong.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
		btnPhong.setForeground(new java.awt.Color(255, 255, 153));
		btnPhong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PhongKham/Hinh/emergency-room.png"))); // NOI18N
		btnPhong.setText(" Phòng");
		btnPhong.setBorder(null);
		btnPhong.setFocusable(false);
		btnPhong.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnPhongActionPerformed(evt);
			}
		});

		btnHoaDonThuoc.setBackground(new java.awt.Color(0, 204, 255));
		btnHoaDonThuoc.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
		btnHoaDonThuoc.setForeground(new java.awt.Color(255, 255, 153));
		btnHoaDonThuoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PhongKham/Hinh/clinic-history.png"))); // NOI18N
		btnHoaDonThuoc.setText("Hóa Đơn Thuốc");
		btnHoaDonThuoc.setBorder(null);
		btnHoaDonThuoc.setFocusable(false);
		btnHoaDonThuoc.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnHoaDonThuocActionPerformed(evt);
			}
		});

		btnThuVienPhi.setBackground(new java.awt.Color(0, 204, 255));
		btnThuVienPhi.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
		btnThuVienPhi.setForeground(new java.awt.Color(255, 255, 153));
		btnThuVienPhi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PhongKham/Hinh/money-bag.png"))); // NOI18N
		btnThuVienPhi.setText(" Thu Viện Phí");
		btnThuVienPhi.setBorder(null);
		btnThuVienPhi.setFocusable(false);
		btnThuVienPhi.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnThuVienPhiActionPerformed(evt);
			}
		});

		jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

		jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

		jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addGap(24, 24, 24).addComponent(btnTiepNhan)
						.addGap(18, 18, 18)
						.addComponent(btnKhamBenh, javax.swing.GroupLayout.PREFERRED_SIZE, 110,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
						.addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(32, 32, 32).addComponent(btnBenhNhan).addGap(28, 28, 28)
						.addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(38, 38, 38)
						.addComponent(btnNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 110,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(29, 29, 29)
						.addComponent(btnLichKham, javax.swing.GroupLayout.PREFERRED_SIZE, 110,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(27, 27, 27)
						.addComponent(btnThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 110,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(18, 18, 18)
						.addComponent(btnThietBi, javax.swing.GroupLayout.PREFERRED_SIZE, 110,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(18, 18, 18)
						.addComponent(btnPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 110,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(18, 18, 18)
						.addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 2,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(28, 28, 28).addComponent(btnHoaDonThuoc).addGap(18, 18, 18).addComponent(btnThuVienPhi,
								javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(33, 33, 33)));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
				.addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
				.addGroup(jPanel1Layout.createSequentialGroup().addContainerGap()
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(btnThietBi, javax.swing.GroupLayout.PREFERRED_SIZE, 40,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(btnPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 40,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(btnKhamBenh, javax.swing.GroupLayout.PREFERRED_SIZE, 40,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(btnThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 40,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(btnThuVienPhi, javax.swing.GroupLayout.PREFERRED_SIZE, 40,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(btnBenhNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 40,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(btnNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 40,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(btnTiepNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 40,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(btnHoaDonThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 40,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(btnLichKham, javax.swing.GroupLayout.PREFERRED_SIZE, 40,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addContainerGap(20, Short.MAX_VALUE))
				.addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING));

		QuanLy.add(jPanel1, java.awt.BorderLayout.PAGE_START);

		parentpanel.setBackground(new java.awt.Color(204, 255, 255));
		parentpanel.setPreferredSize(new java.awt.Dimension(1630, 900));
		parentpanel.setLayout(new java.awt.CardLayout(1, 1));

		TrangChu2.setBackground(new java.awt.Color(51, 255, 51));
		TrangChu2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
		TrangChu2.setPreferredSize(new java.awt.Dimension(1600, 850));

		jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PhongKham/Hinh/TrangChu.png"))); // NOI18N
		jLabel3.setPreferredSize(new java.awt.Dimension(1600, 850));

		javax.swing.GroupLayout TrangChu2Layout = new javax.swing.GroupLayout(TrangChu2);
		TrangChu2.setLayout(TrangChu2Layout);
		TrangChu2Layout.setHorizontalGroup(
				TrangChu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
						javax.swing.GroupLayout.Alignment.TRAILING,
						TrangChu2Layout.createSequentialGroup()
								.addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 1655, Short.MAX_VALUE)
								.addContainerGap()));
		TrangChu2Layout.setVerticalGroup(TrangChu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 719, Short.MAX_VALUE));

		parentpanel.add(TrangChu2, "card3");

		TiepNhanBNJPan.setPreferredSize(new java.awt.Dimension(1600, 850));

		javax.swing.GroupLayout TiepNhanBNJPanLayout = new javax.swing.GroupLayout(TiepNhanBNJPan);
		TiepNhanBNJPan.setLayout(TiepNhanBNJPanLayout);
		TiepNhanBNJPanLayout.setHorizontalGroup(TiepNhanBNJPanLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 1521, Short.MAX_VALUE));
		TiepNhanBNJPanLayout.setVerticalGroup(TiepNhanBNJPanLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 719, Short.MAX_VALUE));

		parentpanel.add(TiepNhanBNJPan, "card8");

		KhamBenhJPan.setPreferredSize(new java.awt.Dimension(1600, 850));

		javax.swing.GroupLayout KhamBenhJPanLayout = new javax.swing.GroupLayout(KhamBenhJPan);
		KhamBenhJPan.setLayout(KhamBenhJPanLayout);
		KhamBenhJPanLayout.setHorizontalGroup(KhamBenhJPanLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 1521, Short.MAX_VALUE));
		KhamBenhJPanLayout.setVerticalGroup(KhamBenhJPanLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 719, Short.MAX_VALUE));

		parentpanel.add(KhamBenhJPan, "card9");

		NhanVienJPan.setBackground(new java.awt.Color(204, 204, 204));
		NhanVienJPan.setPreferredSize(new java.awt.Dimension(1600, 850));

		javax.swing.GroupLayout NhanVienJPanLayout = new javax.swing.GroupLayout(NhanVienJPan);
		NhanVienJPan.setLayout(NhanVienJPanLayout);
		NhanVienJPanLayout.setHorizontalGroup(NhanVienJPanLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 1521, Short.MAX_VALUE));
		NhanVienJPanLayout.setVerticalGroup(NhanVienJPanLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 719, Short.MAX_VALUE));

		parentpanel.add(NhanVienJPan, "card3");

		javax.swing.GroupLayout BenhNhanJPanLayout = new javax.swing.GroupLayout(BenhNhanJPan);
		BenhNhanJPan.setLayout(BenhNhanJPanLayout);
		BenhNhanJPanLayout.setHorizontalGroup(BenhNhanJPanLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 1521, Short.MAX_VALUE));
		BenhNhanJPanLayout.setVerticalGroup(BenhNhanJPanLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 0, Short.MAX_VALUE));

		parentpanel.add(BenhNhanJPan, "card11");

		LichKhamJPan.setPreferredSize(new java.awt.Dimension(1600, 850));

		javax.swing.GroupLayout LichKhamJPanLayout = new javax.swing.GroupLayout(LichKhamJPan);
		LichKhamJPan.setLayout(LichKhamJPanLayout);
		LichKhamJPanLayout.setHorizontalGroup(LichKhamJPanLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 1521, Short.MAX_VALUE));
		LichKhamJPanLayout.setVerticalGroup(LichKhamJPanLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 719, Short.MAX_VALUE));

		parentpanel.add(LichKhamJPan, "card2");

		ThuocJPan.setPreferredSize(new java.awt.Dimension(1600, 850));

		javax.swing.GroupLayout ThuocJPanLayout = new javax.swing.GroupLayout(ThuocJPan);
		ThuocJPan.setLayout(ThuocJPanLayout);
		ThuocJPanLayout.setHorizontalGroup(ThuocJPanLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 1521, Short.MAX_VALUE));
		ThuocJPanLayout.setVerticalGroup(ThuocJPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 719, Short.MAX_VALUE));

		parentpanel.add(ThuocJPan, "card10");

		ThietBiJPan.setPreferredSize(new java.awt.Dimension(1600, 850));

		javax.swing.GroupLayout ThietBiJPanLayout = new javax.swing.GroupLayout(ThietBiJPan);
		ThietBiJPan.setLayout(ThietBiJPanLayout);
		ThietBiJPanLayout.setHorizontalGroup(ThietBiJPanLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 1521, Short.MAX_VALUE));
		ThietBiJPanLayout.setVerticalGroup(ThietBiJPanLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 719, Short.MAX_VALUE));

		parentpanel.add(ThietBiJPan, "card7");

		PhongJPan.setPreferredSize(new java.awt.Dimension(1600, 850));

		javax.swing.GroupLayout PhongJPanLayout = new javax.swing.GroupLayout(PhongJPan);
		PhongJPan.setLayout(PhongJPanLayout);
		PhongJPanLayout.setHorizontalGroup(PhongJPanLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 1521, Short.MAX_VALUE));
		PhongJPanLayout.setVerticalGroup(PhongJPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 719, Short.MAX_VALUE));

		parentpanel.add(PhongJPan, "card5");

		HoaDonThuocJPan.setBackground(new java.awt.Color(93, 167, 219));

		javax.swing.GroupLayout HoaDonThuocJPanLayout = new javax.swing.GroupLayout(HoaDonThuocJPan);
		HoaDonThuocJPan.setLayout(HoaDonThuocJPanLayout);
		HoaDonThuocJPanLayout.setHorizontalGroup(HoaDonThuocJPanLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 1521, Short.MAX_VALUE));
		HoaDonThuocJPanLayout.setVerticalGroup(HoaDonThuocJPanLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 719, Short.MAX_VALUE));

		parentpanel.add(HoaDonThuocJPan, "card12");

		ThuVienPhiJPan.setBackground(new java.awt.Color(51, 204, 255));
		ThuVienPhiJPan.setPreferredSize(new java.awt.Dimension(1600, 850));

		javax.swing.GroupLayout ThuVienPhiJPanLayout = new javax.swing.GroupLayout(ThuVienPhiJPan);
		ThuVienPhiJPan.setLayout(ThuVienPhiJPanLayout);
		ThuVienPhiJPanLayout.setHorizontalGroup(ThuVienPhiJPanLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 1521, Short.MAX_VALUE));
		ThuVienPhiJPanLayout.setVerticalGroup(ThuVienPhiJPanLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 719, Short.MAX_VALUE));

		parentpanel.add(ThuVienPhiJPan, "card6");

		QuanLy.add(parentpanel, java.awt.BorderLayout.CENTER);

		Menu.addTab("Quản Lý", QuanLy);

		ThongKe.setLayout(new java.awt.BorderLayout());

		jPanel4.setBackground(new java.awt.Color(0, 204, 255));
		jPanel4.setPreferredSize(new java.awt.Dimension(1645, 70));

		btnThongKeNV.setBackground(new java.awt.Color(0, 204, 255));
		btnThongKeNV.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
		btnThongKeNV.setForeground(new java.awt.Color(255, 255, 153));
		btnThongKeNV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PhongKham/Hinh/tkNhanVien.png"))); // NOI18N
		btnThongKeNV.setText("Thống Kê Nhân Viên");
		btnThongKeNV.setBorder(null);
		btnThongKeNV.setFocusable(false);
		btnThongKeNV.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnThongKeNVActionPerformed(evt);
			}
		});

		btnThongKeBN.setBackground(new java.awt.Color(0, 204, 255));
		btnThongKeBN.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
		btnThongKeBN.setForeground(new java.awt.Color(255, 255, 153));
		btnThongKeBN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PhongKham/Hinh/stats.png"))); // NOI18N
		btnThongKeBN.setText("Thống Kê Bệnh Nhân");
		btnThongKeBN.setBorder(null);
		btnThongKeBN.setFocusable(false);
		btnThongKeBN.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnThongKeBNActionPerformed(evt);
			}
		});

		btnThongKeThuoc.setBackground(new java.awt.Color(0, 204, 255));
		btnThongKeThuoc.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
		btnThongKeThuoc.setForeground(new java.awt.Color(255, 255, 153));
		btnThongKeThuoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PhongKham/Hinh/tkBenhNhan.png"))); // NOI18N
		btnThongKeThuoc.setText("Thống Kê Thuốc");
		btnThongKeThuoc.setBorder(null);
		btnThongKeThuoc.setFocusable(false);
		btnThongKeThuoc.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnThongKeThuocActionPerformed(evt);
			}
		});

		btnThongKeThietBi.setBackground(new java.awt.Color(0, 204, 255));
		btnThongKeThietBi.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
		btnThongKeThietBi.setForeground(new java.awt.Color(255, 255, 153));
		btnThongKeThietBi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PhongKham/Hinh/tkThietbi.png"))); // NOI18N
		btnThongKeThietBi.setText("Thống Kê Thiết Bị");
		btnThongKeThietBi.setBorder(null);
		btnThongKeThietBi.setFocusable(false);
		btnThongKeThietBi.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnThongKeThietBiActionPerformed(evt);
			}
		});

		btnThongKeDichVu.setBackground(new java.awt.Color(0, 204, 255));
		btnThongKeDichVu.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
		btnThongKeDichVu.setForeground(new java.awt.Color(255, 255, 153));
		btnThongKeDichVu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PhongKham/Hinh/tkDichVu.png"))); // NOI18N
		btnThongKeDichVu.setText("Thống Kê Dịch Vụ");
		btnThongKeDichVu.setBorder(null);
		btnThongKeDichVu.setFocusable(false);
		btnThongKeDichVu.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnThongKeDichVuActionPerformed(evt);
			}
		});

		btnThongKeDT.setBackground(new java.awt.Color(0, 204, 255));
		btnThongKeDT.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
		btnThongKeDT.setForeground(new java.awt.Color(255, 255, 153));
		btnThongKeDT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PhongKham/Hinh/tkDoanhThu.png"))); // NOI18N
		btnThongKeDT.setText("Thống Kê Doanh Thu");
		btnThongKeDT.setBorder(null);
		btnThongKeDT.setFocusable(false);
		btnThongKeDT.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnThongKeDTActionPerformed(evt);
			}
		});

		jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);

		jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);

		jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);

		jSeparator7.setOrientation(javax.swing.SwingConstants.VERTICAL);

		jSeparator8.setOrientation(javax.swing.SwingConstants.VERTICAL);

		javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
		jPanel4.setLayout(jPanel4Layout);
		jPanel4Layout.setHorizontalGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel4Layout.createSequentialGroup().addGap(32, 32, 32)
						.addComponent(btnThongKeNV, javax.swing.GroupLayout.PREFERRED_SIZE, 179,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(18, 18, 18)
						.addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 14,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(27, 27, 27)
						.addComponent(btnThongKeBN, javax.swing.GroupLayout.PREFERRED_SIZE, 185,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(26, 26, 26)
						.addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 14,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(18, 18, 18)
						.addComponent(btnThongKeThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 183,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(28, 28, 28)
						.addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 14,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(18, 18, 18)
						.addComponent(btnThongKeThietBi, javax.swing.GroupLayout.PREFERRED_SIZE, 177,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(35, 35, 35)
						.addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 14,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(18, 18, 18)
						.addComponent(btnThongKeDichVu, javax.swing.GroupLayout.PREFERRED_SIZE, 195,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
						.addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 14,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(26, 26, 26).addComponent(btnThongKeDT, javax.swing.GroupLayout.PREFERRED_SIZE, 190,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(55, 55, 55)));
		jPanel4Layout.setVerticalGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.TRAILING)
				.addComponent(jSeparator5, javax.swing.GroupLayout.Alignment.TRAILING)
				.addComponent(jSeparator6, javax.swing.GroupLayout.Alignment.TRAILING)
				.addComponent(jSeparator7, javax.swing.GroupLayout.Alignment.TRAILING)
				.addComponent(jSeparator8, javax.swing.GroupLayout.Alignment.TRAILING)
				.addGroup(jPanel4Layout.createSequentialGroup().addContainerGap()
						.addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(btnThongKeBN, javax.swing.GroupLayout.PREFERRED_SIZE, 40,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(btnThongKeThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 40,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(btnThongKeNV, javax.swing.GroupLayout.PREFERRED_SIZE, 40,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(btnThongKeThietBi, javax.swing.GroupLayout.PREFERRED_SIZE, 40,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(btnThongKeDT, javax.swing.GroupLayout.PREFERRED_SIZE, 40,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(btnThongKeDichVu, javax.swing.GroupLayout.PREFERRED_SIZE, 40,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addContainerGap(20, Short.MAX_VALUE)));

		ThongKe.add(jPanel4, java.awt.BorderLayout.PAGE_START);

		boo.setLayout(new java.awt.CardLayout());

		TrangChu1.setBackground(new java.awt.Color(51, 255, 51));
		TrangChu1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
		TrangChu1.setPreferredSize(new java.awt.Dimension(1600, 850));

		jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PhongKham/Hinh/TrangChu.png"))); // NOI18N
		jLabel2.setPreferredSize(new java.awt.Dimension(1600, 850));

		javax.swing.GroupLayout TrangChu1Layout = new javax.swing.GroupLayout(TrangChu1);
		TrangChu1.setLayout(TrangChu1Layout);
		TrangChu1Layout.setHorizontalGroup(
				TrangChu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
						javax.swing.GroupLayout.Alignment.TRAILING,
						TrangChu1Layout.createSequentialGroup()
								.addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1655, Short.MAX_VALUE)
								.addContainerGap()));
		TrangChu1Layout.setVerticalGroup(TrangChu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(TrangChu1Layout.createSequentialGroup().addComponent(jLabel2,
						javax.swing.GroupLayout.PREFERRED_SIZE, 702, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(0, 19, Short.MAX_VALUE)));

		boo.add(TrangChu1, "card3");

		ThongKeNVJPan.setBackground(new java.awt.Color(255, 255, 255));

		javax.swing.GroupLayout ThongKeNVJPanLayout = new javax.swing.GroupLayout(ThongKeNVJPan);
		ThongKeNVJPan.setLayout(ThongKeNVJPanLayout);
		ThongKeNVJPanLayout.setHorizontalGroup(ThongKeNVJPanLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 1523, Short.MAX_VALUE));
		ThongKeNVJPanLayout.setVerticalGroup(ThongKeNVJPanLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 721, Short.MAX_VALUE));

		boo.add(ThongKeNVJPan, "card5");

		javax.swing.GroupLayout ThongKeBNJPanLayout = new javax.swing.GroupLayout(ThongKeBNJPan);
		ThongKeBNJPan.setLayout(ThongKeBNJPanLayout);
		ThongKeBNJPanLayout.setHorizontalGroup(ThongKeBNJPanLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 1523, Short.MAX_VALUE));
		ThongKeBNJPanLayout.setVerticalGroup(ThongKeBNJPanLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 721, Short.MAX_VALUE));

		boo.add(ThongKeBNJPan, "card5");

		javax.swing.GroupLayout ThongKeTJPanLayout = new javax.swing.GroupLayout(ThongKeTJPan);
		ThongKeTJPan.setLayout(ThongKeTJPanLayout);
		ThongKeTJPanLayout.setHorizontalGroup(ThongKeTJPanLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 1523, Short.MAX_VALUE));
		ThongKeTJPanLayout.setVerticalGroup(ThongKeTJPanLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 721, Short.MAX_VALUE));

		boo.add(ThongKeTJPan, "card6");

		javax.swing.GroupLayout ThongKeTBJPanLayout = new javax.swing.GroupLayout(ThongKeTBJPan);
		ThongKeTBJPan.setLayout(ThongKeTBJPanLayout);
		ThongKeTBJPanLayout.setHorizontalGroup(ThongKeTBJPanLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 1523, Short.MAX_VALUE));
		ThongKeTBJPanLayout.setVerticalGroup(ThongKeTBJPanLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 721, Short.MAX_VALUE));

		boo.add(ThongKeTBJPan, "card6");

		javax.swing.GroupLayout ThongKeDVJPanLayout = new javax.swing.GroupLayout(ThongKeDVJPan);
		ThongKeDVJPan.setLayout(ThongKeDVJPanLayout);
		ThongKeDVJPanLayout.setHorizontalGroup(ThongKeDVJPanLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 1523, Short.MAX_VALUE));
		ThongKeDVJPanLayout.setVerticalGroup(ThongKeDVJPanLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 721, Short.MAX_VALUE));

		boo.add(ThongKeDVJPan, "card7");

		javax.swing.GroupLayout ThongKeDTJPanLayout = new javax.swing.GroupLayout(ThongKeDTJPan);
		ThongKeDTJPan.setLayout(ThongKeDTJPanLayout);
		ThongKeDTJPanLayout.setHorizontalGroup(ThongKeDTJPanLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 1523, Short.MAX_VALUE));
		ThongKeDTJPanLayout.setVerticalGroup(ThongKeDTJPanLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 721, Short.MAX_VALUE));

		boo.add(ThongKeDTJPan, "card2");

		ThongKe.add(boo, java.awt.BorderLayout.CENTER);

		Menu.addTab("Thống Kê", ThongKe);

		TroGiup.setLayout(new java.awt.BorderLayout());

		jPanel2.setBackground(new java.awt.Color(0, 204, 255));
		jPanel2.setPreferredSize(new java.awt.Dimension(942, 70));

		btnHuongDan.setBackground(new java.awt.Color(0, 204, 255));
		btnHuongDan.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
		btnHuongDan.setForeground(new java.awt.Color(255, 255, 153));
		btnHuongDan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PhongKham/Hinh/guide.png"))); // NOI18N
		btnHuongDan.setText("Hướng Dẫn");
		btnHuongDan.setBorder(null);
		btnHuongDan.setFocusable(false);
		btnHuongDan.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnHuongDanActionPerformed(evt);
			}
		});

		btnGioiThieu.setBackground(new java.awt.Color(0, 204, 255));
		btnGioiThieu.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
		btnGioiThieu.setForeground(new java.awt.Color(255, 255, 153));
		btnGioiThieu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PhongKham/Hinh/lightbulb.png"))); // NOI18N
		btnGioiThieu.setText("Giới Thiệu");
		btnGioiThieu.setBorder(null);
		btnGioiThieu.setFocusable(false);
		btnGioiThieu.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnGioiThieuActionPerformed(evt);
			}
		});

		btnDichVu.setBackground(new java.awt.Color(0, 204, 255));
		btnDichVu.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
		btnDichVu.setForeground(new java.awt.Color(255, 255, 153));
		btnDichVu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PhongKham/Hinh/24-hours.png"))); // NOI18N
		btnDichVu.setText("Dịch Vụ");
		btnDichVu.setBorder(null);
		btnDichVu.setFocusable(false);
		btnDichVu.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnDichVuActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup().addContainerGap().addComponent(btnHuongDan)
						.addGap(18, 18, 18)
						.addComponent(btnGioiThieu, javax.swing.GroupLayout.PREFERRED_SIZE, 113,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(18, 18, 18).addComponent(btnDichVu, javax.swing.GroupLayout.PREFERRED_SIZE, 100,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(1151, Short.MAX_VALUE)));
		jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup().addContainerGap()
						.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(btnHuongDan, javax.swing.GroupLayout.PREFERRED_SIZE, 40,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(btnGioiThieu, javax.swing.GroupLayout.PREFERRED_SIZE, 40,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(btnDichVu, javax.swing.GroupLayout.PREFERRED_SIZE, 40,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addContainerGap(20, Short.MAX_VALUE)));

		TroGiup.add(jPanel2, java.awt.BorderLayout.PAGE_START);

		bo.setLayout(new java.awt.CardLayout());

		TrangChu3.setBackground(new java.awt.Color(51, 255, 51));
		TrangChu3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
		TrangChu3.setPreferredSize(new java.awt.Dimension(1600, 850));

		jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PhongKham/Hinh/TrangChu.png"))); // NOI18N
		jLabel4.setPreferredSize(new java.awt.Dimension(1600, 850));

		javax.swing.GroupLayout TrangChu3Layout = new javax.swing.GroupLayout(TrangChu3);
		TrangChu3.setLayout(TrangChu3Layout);
		TrangChu3Layout.setHorizontalGroup(
				TrangChu3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
						javax.swing.GroupLayout.Alignment.TRAILING,
						TrangChu3Layout.createSequentialGroup()
								.addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 1769, Short.MAX_VALUE)
								.addContainerGap()));
		TrangChu3Layout.setVerticalGroup(TrangChu3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(TrangChu3Layout.createSequentialGroup().addComponent(jLabel4,
						javax.swing.GroupLayout.PREFERRED_SIZE, 702, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(0, 19, Short.MAX_VALUE)));

		bo.add(TrangChu3, "card3");

		javax.swing.GroupLayout HuongDanJPanLayout = new javax.swing.GroupLayout(HuongDanJPan);
		HuongDanJPan.setLayout(HuongDanJPanLayout);
		HuongDanJPanLayout.setHorizontalGroup(HuongDanJPanLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 1523, Short.MAX_VALUE));
		HuongDanJPanLayout.setVerticalGroup(HuongDanJPanLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 721, Short.MAX_VALUE));

		bo.add(HuongDanJPan, "card4");

		javax.swing.GroupLayout GioiThieuJPanLayout = new javax.swing.GroupLayout(GioiThieuJPan);
		GioiThieuJPan.setLayout(GioiThieuJPanLayout);
		GioiThieuJPanLayout.setHorizontalGroup(GioiThieuJPanLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 1523, Short.MAX_VALUE));
		GioiThieuJPanLayout.setVerticalGroup(GioiThieuJPanLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 721, Short.MAX_VALUE));

		bo.add(GioiThieuJPan, "card3");

		javax.swing.GroupLayout DichVuJPanLayout = new javax.swing.GroupLayout(DichVuJPan);
		DichVuJPan.setLayout(DichVuJPanLayout);
		DichVuJPanLayout.setHorizontalGroup(DichVuJPanLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 1523, Short.MAX_VALUE));
		DichVuJPanLayout.setVerticalGroup(DichVuJPanLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 721, Short.MAX_VALUE));

		bo.add(DichVuJPan, "card2");

		TroGiup.add(bo, java.awt.BorderLayout.CENTER);

		Menu.addTab("Trơ Giúp", TroGiup);

		getContentPane().add(Menu, java.awt.BorderLayout.CENTER);

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void btnDoiMatKhauActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnDoiMatKhauActionPerformed
		if (Auth.isLogin() && user.getChucVu().equalsIgnoreCase("Bác sĩ")) {
			// TODO add your handling code here:
			cha.removeAll();
			cha.add(DoiMatKhauJPan);
			cha.repaint();
			cha.revalidate();
			DoiMatKhauJPan.add(new DoiMatKhauGD(), "DoiMatKhau");
			card.show(DoiMatKhauJPan, "DoiMatKhau");
		} else if (Auth.isLogin() && user.getChucVu().equalsIgnoreCase("Y tá")) {
			cha.removeAll();
			cha.add(DoiMatKhauJPan);
			cha.repaint();
			cha.revalidate();
			DoiMatKhauJPan.add(new DoiMatKhauGD(), "DoiMatKhau");
			card.show(DoiMatKhauJPan, "DoiMatKhau");
		} else if (Auth.isLogin() && user.getChucVu().equalsIgnoreCase("Ban quản lý")) {
			cha.removeAll();
			cha.add(DoiMatKhauJPan);
			cha.repaint();
			cha.revalidate();
			DoiMatKhauJPan.add(new DoiMatKhauGD(), "DoiMatKhau");
			card.show(DoiMatKhauJPan, "DoiMatKhau");
		} else {
			MsgBox.alert(this, "Vui lòng Dùng Tài Khoản đủ quyền truy cập");
		}
	}// GEN-LAST:event_btnDoiMatKhauActionPerformed

	private void btnTTKActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnTTKActionPerformed
		// TODO add your handling code here:
		if (Auth.isLogin() && user.getChucVu().equalsIgnoreCase("Bác sĩ")) {
			cha.removeAll();
			cha.add(TaoTaiKhoanJPan);
			cha.repaint();
			cha.revalidate();
			TaoTaiKhoanJPan.add(new TaoTaiKhoanGD(), "TaoTaiKhoan");
			card.show(TaoTaiKhoanJPan, "TaoTaiKhoan");
		} else {
			MsgBox.alert(this, "Vui lòng Dùng Tài Khoản đủ quyền truy cập");
		}
	}// GEN-LAST:event_btnTTKActionPerformed

	private void btnDangXuatActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnDangXuatActionPerformed
		// TODO add your handling code here:
//        cha.removeAll();
//        cha.add(DangXuatJPan);
//        cha.repaint();
//        cha.revalidate();
//        new DangXuat(this, true).setVisible(true);
		this.dangXuat();
	}// GEN-LAST:event_btnDangXuatActionPerformed

	private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnThoatActionPerformed
		// TODO add your handling code here:
		this.ketThuc();

	}// GEN-LAST:event_btnThoatActionPerformed

	private void btnKhamBenhActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnKhamBenhActionPerformed
		// TODO add your handling code here:
		if (Auth.isLogin() && user.getChucVu().equalsIgnoreCase("Bác sĩ")) {
			parentpanel.removeAll();
			parentpanel.add(KhamBenhJPan);
			parentpanel.repaint();
			parentpanel.revalidate();
			KhamBenhJPan.add(new KhamBenhGD(), "KhamBenh");
			card.show(KhamBenhJPan, "KhamBenh");
		} else if (Auth.isLogin() && user.getChucVu().equalsIgnoreCase("Bác sĩ")) {
			parentpanel.removeAll();
			parentpanel.add(KhamBenhJPan);
			parentpanel.repaint();
			parentpanel.revalidate();
			KhamBenhJPan.add(new KhamBenhGD(), "KhamBenh");
			card.show(KhamBenhJPan, "KhamBenh");

		} else {
			MsgBox.alert(this, "Vui lòng Dùng Tài Khoản đủ quyền truy cập");
		}
	}// GEN-LAST:event_btnKhamBenhActionPerformed

	private void btnLichKhamActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnLichKhamActionPerformed
		// TODO add your handling code here:
		if (Auth.isLogin() && user.getChucVu().equalsIgnoreCase("Y tá")) {
			parentpanel.removeAll();
			parentpanel.add(LichKhamJPan);
			parentpanel.repaint();
			parentpanel.revalidate();
			LichKhamJPan.add(new LichKhamGD(), "LichKham");
			card.show(LichKhamJPan, "LichKham");
		} else if (Auth.isLogin() && user.getChucVu().equalsIgnoreCase("Bác sĩ")) {
			parentpanel.removeAll();
			parentpanel.add(LichKhamJPan);
			parentpanel.repaint();
			parentpanel.revalidate();
			LichKhamJPan.add(new LichKhamGD(), "LichKham");
			card.show(LichKhamJPan, "LichKham");
		} else {
			MsgBox.alert(this, "Vui lòng Dùng Tài Khoản đủ quyền truy cập");
		}
	}// GEN-LAST:event_btnLichKhamActionPerformed

	private void btnThuocActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnThuocActionPerformed
		// TODO add your handling code here:
		if (Auth.isLogin() && user.getChucVu().equalsIgnoreCase("Bác sĩ")) {
			parentpanel.removeAll();
			parentpanel.add(ThuocJPan);
			parentpanel.repaint();
			parentpanel.revalidate();
			ThuocJPan.add(new ThuocGD(), "Thuoc");
			card.show(ThuocJPan, "Thuoc");
		} else if (Auth.isLogin() && user.getChucVu().equalsIgnoreCase("Y tá")) {
			parentpanel.removeAll();
			parentpanel.add(ThuocJPan);
			parentpanel.repaint();
			parentpanel.revalidate();
			ThuocJPan.add(new ThuocGD(), "Thuoc");
			card.show(ThuocJPan, "Thuoc");
		} else {
			MsgBox.alert(this, "Vui lòng Dùng Tài Khoản đủ quyền truy cập");
		}

	}// GEN-LAST:event_btnThuocActionPerformed

	private void btnThietBiActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnThietBiActionPerformed
		// TODO add your handling code here:
		if (Auth.isLogin() && user.getChucVu().equalsIgnoreCase("Y tá")) {
			parentpanel.removeAll();
			parentpanel.add(ThietBiJPan);
			parentpanel.repaint();
			parentpanel.revalidate();
			ThietBiJPan.add(new ThietBiGD(), "ThietBi");
			card.show(ThietBiJPan, "ThietBi");
		}

		else if (Auth.isLogin() && user.getChucVu().equalsIgnoreCase("Bác sĩ")) {
			parentpanel.removeAll();
			parentpanel.add(ThietBiJPan);
			parentpanel.repaint();
			parentpanel.revalidate();
			ThietBiJPan.add(new ThietBiGD(), "ThietBi");
			card.show(ThietBiJPan, "ThietBi");
		} else {
			MsgBox.alert(this, "Vui lòng Dùng Tài Khoản đủ quyền truy cập");
		}
	}// GEN-LAST:event_btnThietBiActionPerformed

	private void btnPhongActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnPhongActionPerformed
		// TODO add your handling code here:
		if (Auth.isLogin() && user.getChucVu().equalsIgnoreCase("Y tá")) {
			parentpanel.removeAll();
			parentpanel.add(PhongJPan);
			parentpanel.repaint();
			parentpanel.revalidate();
			PhongJPan.add(new PhongGD(), "Phong");
			card.show(PhongJPan, "Phong");
		} else if (Auth.isLogin() && user.getChucVu().equalsIgnoreCase("Bác sĩ")) {
			parentpanel.removeAll();
			parentpanel.add(PhongJPan);
			parentpanel.repaint();
			parentpanel.revalidate();
			PhongJPan.add(new PhongGD(), "Phong");
			card.show(PhongJPan, "Phong");
		} else {
			MsgBox.alert(this, "Vui lòng Dùng Tài Khoản đủ quyền truy cập");
		}
	}// GEN-LAST:event_btnPhongActionPerformed

	private void btnThuVienPhiActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnThuVienPhiActionPerformed
		// TODO add your handling code here:
		if (Auth.isLogin() && user.getChucVu().equalsIgnoreCase("Bác sĩ")) {
			parentpanel.removeAll();
			parentpanel.add(ThuVienPhiJPan);
			parentpanel.repaint();
			parentpanel.revalidate();
			ThuVienPhiJPan.add(new ThuVienPhiGD(), "ThuVienPhi");
			card.show(ThuVienPhiJPan, "ThuVienPhi");
		} else if (Auth.isLogin() && user.getChucVu().equalsIgnoreCase("Y tá")) {
			parentpanel.removeAll();
			parentpanel.add(ThuVienPhiJPan);
			parentpanel.repaint();
			parentpanel.revalidate();
			ThuVienPhiJPan.add(new ThuVienPhiGD(), "ThuVienPhi");
			card.show(ThuVienPhiJPan, "ThuVienPhi");
		} else {
			MsgBox.alert(this, "Vui lòng Dùng Tài Khoản đủ quyền truy cập");
		}
	}// GEN-LAST:event_btnThuVienPhiActionPerformed

	private void btnNhanVienActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnNhanVienActionPerformed

		if (Auth.isLogin() && user.getChucVu().equalsIgnoreCase("Bác sĩ")) {
			parentpanel.removeAll();
			parentpanel.add(NhanVienJPan);
			parentpanel.repaint();
			parentpanel.revalidate();
			NhanVienJPan.add(new NhanVienGD(), "NhanVien");
			card.show(NhanVienJPan, "NhanVien");
		} else {
			MsgBox.alert(this, "Vui lòng Dùng Tài Khoản đủ quyền truy cập");
		}
	}// GEN-LAST:event_btnNhanVienActionPerformed

	private void btnThongKeNVActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnThongKeNVActionPerformed
		// TODO add your handling code here:
		if (Auth.isLogin() && user.getChucVu().equalsIgnoreCase("Bác sĩ")) {
			boo.removeAll();
			boo.add(ThongKeNVJPan);
			boo.repaint();
			boo.revalidate();
			ThongKeNVJPan.add(new ThongKeNV(), "TiepNhan");
			card.show(ThongKeNVJPan, "TiepNhan");
		} else {
			MsgBox.alert(this, "Vui lòng Dùng Tài Khoản đủ quyền truy cập");
		}
	}// GEN-LAST:event_btnThongKeNVActionPerformed

	private void btnTiepNhanActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnTiepNhanActionPerformed
		// TODO add your handling code here:
		if (Auth.isLogin() && user.getChucVu().equalsIgnoreCase("Y tá")) {
			parentpanel.removeAll();
			parentpanel.add(TiepNhanBNJPan);
			parentpanel.repaint();
			parentpanel.revalidate();
			TiepNhanBNJPan.add(new TiepNhan(), "TiepNhan");
			card.show(TiepNhanBNJPan, "TiepNhan");
		} else if (Auth.isLogin() && user.getChucVu().equalsIgnoreCase("Bác sĩ")) {
			parentpanel.removeAll();
			parentpanel.add(TiepNhanBNJPan);
			parentpanel.repaint();
			parentpanel.revalidate();
			TiepNhanBNJPan.add(new TiepNhan(), "TiepNhan");
			card.show(TiepNhanBNJPan, "TiepNhan");
		} else {
			MsgBox.alert(this, "Vui lòng Dùng Tài Khoản đủ quyền truy cập");
		}
	}// GEN-LAST:event_btnTiepNhanActionPerformed

	private void btnBenhNhanActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnBenhNhanActionPerformed
		// TODO add your handling code here:
		if (Auth.isLogin() && user.getChucVu().equalsIgnoreCase("Y tá")) {
			parentpanel.removeAll();
			parentpanel.add(TiepNhanBNJPan);
			parentpanel.repaint();
			parentpanel.revalidate();
			TiepNhanBNJPan.add(new BenhNhanGD(), "BenhNhan");
			card.show(TiepNhanBNJPan, "BenhNhan");
		} else if (Auth.isLogin() && user.getChucVu().equalsIgnoreCase("Bác sĩ")) {
			parentpanel.removeAll();
			parentpanel.add(TiepNhanBNJPan);
			parentpanel.repaint();
			parentpanel.revalidate();
			TiepNhanBNJPan.add(new BenhNhanGD(), "BenhNhan");
			card.show(TiepNhanBNJPan, "BenhNhan");
		} else {
			MsgBox.alert(this, "Vui lòng Dùng Tài Khoản đủ quyền truy cập");
		}
	}// GEN-LAST:event_btnBenhNhanActionPerformed

	private void btnThongKeThietBiActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnThongKeThietBiActionPerformed
		// TODO add your handling code here:
		if (Auth.isLogin() && user.getChucVu().equalsIgnoreCase("Bác sĩ")) {
			boo.removeAll();
			boo.add(ThongKeTBJPan);
			boo.repaint();
			boo.revalidate();
			ThongKeTBJPan.add(new ThongKeTB(), "TiepNhan");
			card.show(ThongKeTBJPan, "TiepNhan");
		} else {
			MsgBox.alert(this, "Vui lòng Dùng Tài Khoản đủ quyền truy cập");
		}
	}// GEN-LAST:event_btnThongKeThietBiActionPerformed

	private void btnThongKeDichVuActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnThongKeDichVuActionPerformed
		// TODO add your handling code here:
		if (Auth.isLogin() && user.getChucVu().equalsIgnoreCase("Bác sĩ")) {
			boo.removeAll();
			boo.add(ThongKeDVJPan);
			boo.repaint();
			boo.revalidate();
			ThongKeDVJPan.add(new ThongKeDV(), "TKDV");
			card.show(ThongKeDVJPan, "TKDV");
		} else {
			MsgBox.alert(this, "Vui lòng Dùng Tài Khoản đủ quyền truy cập");
		}
	}// GEN-LAST:event_btnThongKeDichVuActionPerformed

	private void btnThongKeDTActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnThongKeDTActionPerformed
		// TODO add your handling code here:
		if (Auth.isLogin() && user.getChucVu().equalsIgnoreCase("Bác sĩ")) {
			boo.removeAll();
			boo.add(ThongKeDTJPan);
			boo.repaint();
			boo.revalidate();
			ThongKeDTJPan.add(new ThongKeDT(), "TKDT");
			card.show(ThongKeDTJPan, "TKDT");
		} else {
			MsgBox.alert(this, "Vui lòng Dùng Tài Khoản đủ quyền truy cập");
		}
	}// GEN-LAST:event_btnThongKeDTActionPerformed

	private void btnGioiThieuActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnGioiThieuActionPerformed
		// TODO add your handling code here:
		bo.removeAll();
		bo.add(GioiThieuJPan);
		bo.repaint();
		bo.revalidate();
		GioiThieuJPan.add(new GioiThieu(), "TiepNhan");
		card.show(GioiThieuJPan, "TiepNhan");
	}// GEN-LAST:event_btnGioiThieuActionPerformed

	private void btnThongKeBNActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnThongKeBNActionPerformed
		// TODO add your handling code here:
		if (Auth.isLogin() && user.getChucVu().equalsIgnoreCase("Bác sĩ")) {
			boo.removeAll();
			boo.add(ThongKeBNJPan);
			boo.repaint();
			boo.revalidate();
			ThongKeBNJPan.add(new ThongKeBN(), "TiepNhan");
			card.show(ThongKeBNJPan, "TiepNhan");
		} else {
			MsgBox.alert(this, "Vui lòng Dùng Tài Khoản đủ quyền truy cập");
		}
	}// GEN-LAST:event_btnThongKeBNActionPerformed

	private void btnThongKeThuocActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnThongKeThuocActionPerformed
		// TODO add your handling code here:
		if (Auth.isLogin() && user.getChucVu().equalsIgnoreCase("Bác sĩ")) {
			boo.removeAll();
			boo.add(ThongKeTJPan);
			boo.repaint();
			boo.revalidate();
			ThongKeTJPan.add(new ThongKeThuoc(), "TiepNhan");
			card.show(ThongKeTJPan, "TiepNhan");
		} else {
			MsgBox.alert(this, "Vui lòng Dùng Tài Khoản đủ quyền truy cập");
		}

	}// GEN-LAST:event_btnThongKeThuocActionPerformed

	private void btnHoaDonThuocActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnHoaDonThuocActionPerformed
		// TODO add your handling code here:
		if (Auth.isLogin() && user.getChucVu().equalsIgnoreCase("Bác sĩ")) {
			parentpanel.removeAll();
			parentpanel.add(HoaDonThuocJPan);
			parentpanel.repaint();
			parentpanel.revalidate();
			HoaDonThuocJPan.add(new HoaDonThuocGD(), "HDT");
			card.show(HoaDonThuocJPan, "HDT");
		} else if (Auth.isLogin() && user.getChucVu().equalsIgnoreCase("Bác sĩ")) {
			parentpanel.removeAll();
			parentpanel.add(TiepNhanBNJPan);
			parentpanel.repaint();
			parentpanel.revalidate();
			TiepNhanBNJPan.add(new BenhNhanGD(), "BenhNhan");
			card.show(TiepNhanBNJPan, "BenhNhan");
		} else {
			MsgBox.alert(this, "Vui lòng Dùng Tài Khoản đủ quyền truy cập");
		}
	}// GEN-LAST:event_btnHoaDonThuocActionPerformed

	private void btnDichVuActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnDichVuActionPerformed
		// TODO add your handling code here:
		if (Auth.isLogin() && user.getChucVu().equalsIgnoreCase("Y tá")) {
			bo.removeAll();
			bo.add(DichVuJPan);
			bo.repaint();
			bo.revalidate();
			DichVuJPan.add(new DichVuGD(), "dichvu");
			card.show(DichVuJPan, "dichvu");
		} else if (Auth.isLogin() && user.getChucVu().equalsIgnoreCase("Bác sĩ")) {
			bo.removeAll();
			bo.add(DichVuJPan);
			bo.repaint();
			bo.revalidate();
			DichVuJPan.add(new DichVuGD(), "dichvu");
			card.show(DichVuJPan, "dichvu");
		} else {
			MsgBox.alert(this, "Vui lòng Dùng Tài Khoản đủ quyền truy cập");
		}
	}// GEN-LAST:event_btnDichVuActionPerformed

	private void btnHuongDanActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnHuongDanActionPerformed
		// TODO add your handling code here:
		bo.removeAll();
		bo.add(HuongDanJPan);
		bo.repaint();
		bo.revalidate();
		HuongDanJPan.add(new HuongDan(), "TiepNhan");
		card.show(HuongDanJPan, "TiepNhan");
		this.openHuongDan();
	}// GEN-LAST:event_btnHuongDanActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Windows".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(ClinicPK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(ClinicPK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(ClinicPK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(ClinicPK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new ClinicPK().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JPanel BenhNhanJPan;
	private javax.swing.JPanel DangXuatJPan;
	private javax.swing.JPanel DichVuJPan;
	private javax.swing.JPanel DoiMatKhauJPan;
	private javax.swing.JPanel GioiThieuJPan;
	private javax.swing.JPanel HeThong;
	private javax.swing.JPanel HoaDonThuocJPan;
	private javax.swing.JPanel HuongDanJPan;
	private javax.swing.JPanel KhamBenhJPan;
	private javax.swing.JPanel LichKhamJPan;
	private javax.swing.JTabbedPane Menu;
	private javax.swing.JPanel NhanVienJPan;
	private javax.swing.JPanel PhongJPan;
	private javax.swing.JPanel QuanLy;
	private javax.swing.JPanel TaoTaiKhoanJPan;
	private javax.swing.JPanel ThietBiJPan;
	private javax.swing.JPanel ThongKe;
	private javax.swing.JPanel ThongKeBNJPan;
	private javax.swing.JPanel ThongKeDTJPan;
	private javax.swing.JPanel ThongKeDVJPan;
	private javax.swing.JPanel ThongKeNVJPan;
	private javax.swing.JPanel ThongKeTBJPan;
	private javax.swing.JPanel ThongKeTJPan;
	private javax.swing.JPanel ThuVienPhiJPan;
	private javax.swing.JPanel ThuocJPan;
	private javax.swing.JPanel TiepNhanBNJPan;
	private javax.swing.JPanel TrangChu;
	private javax.swing.JPanel TrangChu1;
	private javax.swing.JPanel TrangChu2;
	private javax.swing.JPanel TrangChu3;
	private javax.swing.JPanel TroGiup;
	private javax.swing.JPanel bo;
	private javax.swing.JPanel boo;
	private javax.swing.JButton btnBenhNhan;
	private javax.swing.JButton btnDangXuat;
	private javax.swing.JButton btnDichVu;
	private javax.swing.JButton btnDoiMatKhau;
	private javax.swing.JButton btnGioiThieu;
	private javax.swing.JButton btnHoaDonThuoc;
	private javax.swing.JButton btnHuongDan;
	private javax.swing.JButton btnKhamBenh;
	private javax.swing.JButton btnLichKham;
	private javax.swing.JButton btnNhanVien;
	private javax.swing.JButton btnPhong;
	private javax.swing.JButton btnTTK;
	private javax.swing.JButton btnThietBi;
	private javax.swing.JButton btnThoat;
	private javax.swing.JButton btnThongKeBN;
	private javax.swing.JButton btnThongKeDT;
	private javax.swing.JButton btnThongKeDichVu;
	private javax.swing.JButton btnThongKeNV;
	private javax.swing.JButton btnThongKeThietBi;
	private javax.swing.JButton btnThongKeThuoc;
	private javax.swing.JButton btnThuVienPhi;
	private javax.swing.JButton btnThuoc;
	private javax.swing.JButton btnTiepNhan;
	private javax.swing.JPanel cha;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JPanel jPanel4;
	private javax.swing.JSeparator jSeparator1;
	private javax.swing.JSeparator jSeparator2;
	private javax.swing.JSeparator jSeparator3;
	private javax.swing.JSeparator jSeparator4;
	private javax.swing.JSeparator jSeparator5;
	private javax.swing.JSeparator jSeparator6;
	private javax.swing.JSeparator jSeparator7;
	private javax.swing.JSeparator jSeparator8;
	private javax.swing.JLabel lblChuChay;
	private javax.swing.JPanel parentpanel;

	// End of variables declaration//GEN-END:variables
	void init() {
		setSize(1650, 1000);
		setLocationRelativeTo(null);

		if (Auth.isLogin() != true) {
			new ChaoGD(this, true).setVisible(true);
			new DangNhap(this, true).setVisible(true);
		}

	}

	void dangXuat() {
//        Auth.clear();
		new DangNhap(this, true).setVisible(true);
	}

	void ketThuc() {
		if (MsgBox.confirm(this, "Bạn muốn kết thúc làm việc?")) {
			System.exit(0);
		}
	}

	void openHuongDan() {
		try {
			Desktop.getDesktop().browse(new File("dist\\help\\index.html").toURI());
		} catch (IOException ex) {
			MsgBox.alert(this, "Không tìm thấy file hướng dẫn!");
		}
	}
}
