/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package PhongKham.ui;

import PhongKham.dao.NhanVienDao;
import PhongKham.entity.NhanVienPK;
import PhongKham.utils.MsgBox;
import PhongKham.utils.XDate;
import PhongKham.utils.XImage;
import java.awt.Color;
import java.io.File;
import java.util.ArrayList;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DELL
 */
public class NhanVienGD extends javax.swing.JPanel {

    DefaultComboBoxModel model;
    ArrayList<NhanVienPK> list = new ArrayList<>();
    String Email = "^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@"
            + "[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$";
      String phonePattern = "^(0|\\+84)(\\s|\\.)?((3[2-9])|(5[689])|(7[06-9])|"
              + "(8[1-689])|(9[0-46-9]))(\\d)(\\s|\\.)?(\\d{3})(\\s|\\.)?(\\d{3})$";
    public NhanVienGD() {
        initComponents();
        init();      
        rdoNam.setSelected(true);
    }
    
     
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        fileChooser = new javax.swing.JFileChooser();
        NhanVien = new javax.swing.JPanel();
        ThongTinBS = new javax.swing.JPanel();
        btnChonAnh = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtMaNV = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtHoTenNV = new javax.swing.JTextField();
        txtCMND = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtSDT = new javax.swing.JTextField();
        txtMaKhoa = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        lblAnhNV = new javax.swing.JLabel();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnMoi = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDiaChi = new javax.swing.JTextArea();
        cboChuyenNganh = new javax.swing.JComboBox<>();
        cboChucVu = new javax.swing.JComboBox<>();
        cboTrinhDo = new javax.swing.JComboBox<>();
        JDCNgayVL = new com.toedter.calendar.JDateChooser();
        JDCNgaySinh = new com.toedter.calendar.JDateChooser();
        jPanel1 = new javax.swing.JPanel();
        rdoNam = new javax.swing.JRadioButton();
        rdoNu = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        txtMaPhong = new javax.swing.JTextField();
        tblbangbacsy = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDanhSachNV = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtTimKiem = new javax.swing.JTextField();

        setBackground(new java.awt.Color(93, 167, 219));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(1530, 900));

        NhanVien.setBackground(new java.awt.Color(93, 167, 219));
        NhanVien.setPreferredSize(new java.awt.Dimension(1600, 900));

        ThongTinBS.setBackground(new java.awt.Color(129, 198, 232));
        ThongTinBS.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông Tin Nhân Viên", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 18))); // NOI18N
        ThongTinBS.setToolTipText("");
        ThongTinBS.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btnChonAnh.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnChonAnh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PhongKham/Hinh/photo.png"))); // NOI18N
        btnChonAnh.setText("Tải Ảnh");
        btnChonAnh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChonAnhActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel3.setText("Mã Nhân Viên");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel4.setText("Họ Tên ");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel5.setText("Ngày Sinh");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel6.setText("Ngày VL");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel7.setText("CMND");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel8.setText("Trình Độ");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Chức Vụ");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel12.setText("Giới Tính");

        txtCMND.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCMNDActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel13.setText("Mã Khoa");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setText("Email");

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel16.setText("SĐT");

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel17.setText("Chuyên Ngành");

        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });

        lblAnhNV.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblAnhNV.setMaximumSize(new java.awt.Dimension(197, 211));

        btnThem.setBackground(new java.awt.Color(125, 229, 237));
        btnThem.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PhongKham/Hinh/add-friend.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnXoa.setBackground(new java.awt.Color(125, 229, 237));
        btnXoa.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PhongKham/Hinh/Delete.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnSua.setBackground(new java.awt.Color(125, 229, 237));
        btnSua.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PhongKham/Hinh/refresh.png"))); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnMoi.setBackground(new java.awt.Color(125, 229, 237));
        btnMoi.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PhongKham/Hinh/new.png"))); // NOI18N
        btnMoi.setText("Mới");
        btnMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoiActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel19.setText("Địa Chỉ");

        txtDiaChi.setColumns(20);
        txtDiaChi.setRows(5);
        jScrollPane2.setViewportView(txtDiaChi);

        cboChuyenNganh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboChuyenNganhActionPerformed(evt);
            }
        });

        cboChucVu.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboChucVuItemStateChanged(evt);
            }
        });
        cboChucVu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboChucVuActionPerformed(evt);
            }
        });

        cboTrinhDo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboTrinhDoActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdoNam);
        rdoNam.setText("Nam");

        buttonGroup1.add(rdoNu);
        rdoNu.setText("Nữ");
        rdoNu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoNuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rdoNam)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(rdoNu))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdoNam)
                    .addComponent(rdoNu))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("MaPhong ");

        javax.swing.GroupLayout ThongTinBSLayout = new javax.swing.GroupLayout(ThongTinBS);
        ThongTinBS.setLayout(ThongTinBSLayout);
        ThongTinBSLayout.setHorizontalGroup(
            ThongTinBSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ThongTinBSLayout.createSequentialGroup()
                .addGroup(ThongTinBSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ThongTinBSLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(btnChonAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ThongTinBSLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblAnhNV, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(75, 75, 75)
                .addGroup(ThongTinBSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7)
                    .addComponent(jLabel12)
                    .addComponent(jLabel8))
                .addGap(40, 40, 40)
                .addGroup(ThongTinBSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cboTrinhDo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHoTenNV, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCMND, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(71, 71, 71)
                .addGroup(ThongTinBSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel5)
                    .addComponent(jLabel17)
                    .addComponent(jLabel16)
                    .addComponent(jLabel6))
                .addGap(27, 27, 27)
                .addGroup(ThongTinBSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cboChuyenNganh, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JDCNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMaKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JDCNgayVL, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66)
                .addGroup(ThongTinBSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ThongTinBSLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(btnXoa)
                        .addGap(50, 50, 50)
                        .addComponent(btnSua)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                        .addComponent(btnMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78))
                    .addGroup(ThongTinBSLayout.createSequentialGroup()
                        .addGroup(ThongTinBSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ThongTinBSLayout.createSequentialGroup()
                                .addGroup(ThongTinBSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel10))
                                .addGap(27, 27, 27)
                                .addGroup(ThongTinBSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cboChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(ThongTinBSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtEmail)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE))))
                            .addGroup(ThongTinBSLayout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(18, 18, 18)
                                .addComponent(txtMaPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ThongTinBSLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnThem)
                .addGap(505, 505, 505))
        );
        ThongTinBSLayout.setVerticalGroup(
            ThongTinBSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ThongTinBSLayout.createSequentialGroup()
                .addGroup(ThongTinBSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ThongTinBSLayout.createSequentialGroup()
                        .addGroup(ThongTinBSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ThongTinBSLayout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(jLabel13))
                            .addGroup(ThongTinBSLayout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(ThongTinBSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)))
                            .addGroup(ThongTinBSLayout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(ThongTinBSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMaKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15))))
                        .addGroup(ThongTinBSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(ThongTinBSLayout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(ThongTinBSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ThongTinBSLayout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addGap(45, 45, 45)
                                        .addComponent(jLabel4))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ThongTinBSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel17)
                                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ThongTinBSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel19)
                                        .addComponent(cboChuyenNganh, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(ThongTinBSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(ThongTinBSLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jLabel11))
                                    .addComponent(txtMaPhong)))
                            .addGroup(ThongTinBSLayout.createSequentialGroup()
                                .addGap(97, 97, 97)
                                .addGroup(ThongTinBSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7)
                                    .addGroup(ThongTinBSLayout.createSequentialGroup()
                                        .addGroup(ThongTinBSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel5)
                                            .addComponent(txtHoTenNV, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(JDCNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(34, 34, 34)
                                        .addGroup(ThongTinBSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txtCMND, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel16)
                                            .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ThongTinBSLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblAnhNV, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(ThongTinBSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ThongTinBSLayout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addGroup(ThongTinBSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(ThongTinBSLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(ThongTinBSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnChonAnh)
                            .addGroup(ThongTinBSLayout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(ThongTinBSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cboTrinhDo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8)
                                    .addGroup(ThongTinBSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(JDCNgayVL, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel6))
                                    .addComponent(jLabel10)
                                    .addComponent(cboChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnThem.getAccessibleContext().setAccessibleName("");
        btnXoa.getAccessibleContext().setAccessibleName("");
        btnSua.getAccessibleContext().setAccessibleName("");
        btnMoi.getAccessibleContext().setAccessibleName("");

        tblbangbacsy.setBackground(new java.awt.Color(129, 198, 232));
        tblbangbacsy.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh Sách Nhân  Viên  ", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 18))); // NOI18N

        tblDanhSachNV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "MaNV", "HoTenNV", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9", "Title 10", "Title 11", "Title 12", "Title 13", "Title 14"
            }
        ));
        tblDanhSachNV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDanhSachNVMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDanhSachNV);

        javax.swing.GroupLayout tblbangbacsyLayout = new javax.swing.GroupLayout(tblbangbacsy);
        tblbangbacsy.setLayout(tblbangbacsyLayout);
        tblbangbacsyLayout.setHorizontalGroup(
            tblbangbacsyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1477, Short.MAX_VALUE)
        );
        tblbangbacsyLayout.setVerticalGroup(
            tblbangbacsyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout NhanVienLayout = new javax.swing.GroupLayout(NhanVien);
        NhanVien.setLayout(NhanVienLayout);
        NhanVienLayout.setHorizontalGroup(
            NhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NhanVienLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(NhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ThongTinBS, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tblbangbacsy, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        NhanVienLayout.setVerticalGroup(
            NhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NhanVienLayout.createSequentialGroup()
                .addComponent(ThongTinBS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tblbangbacsy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 30, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PhongKham/Hinh/search.png"))); // NOI18N
        jLabel1.setText("Find Name : ");

        txtTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimKiemActionPerformed(evt);
            }
        });
        txtTimKiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTimKiemKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 1510, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1153, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(NhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, 634, Short.MAX_VALUE)
                .addGap(214, 214, 214))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnChonAnhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChonAnhActionPerformed
        // TODO add your handling code here:
        this.chonAnh();
    }//GEN-LAST:event_btnChonAnhActionPerformed

    private void txtCMNDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCMNDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCMNDActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void rdoNuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoNuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoNuActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        if(isValidated()){
            this.insert();
        }


//        this.insert();
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        this.delete();
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        this.update();
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoiActionPerformed
        // TODO add your handling code here:
        this.clearForm();
    }//GEN-LAST:event_btnMoiActionPerformed

    public void tblDanhSachNVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDanhSachNVMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 1) {
            this.row = tblDanhSachNV.getSelectedRow();
            this.edit();
        }
    }//GEN-LAST:event_tblDanhSachNVMouseClicked

    private void cboChuyenNganhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboChuyenNganhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboChuyenNganhActionPerformed

    private void cboChucVuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboChucVuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboChucVuActionPerformed

    private void cboTrinhDoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboTrinhDoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboTrinhDoActionPerformed

    public void txtTimKiemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimKiemKeyReleased
        // TODO add your handling code here:
       this.fillTable();
    }//GEN-LAST:event_txtTimKiemKeyReleased

    public void txtTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimKiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimKiemActionPerformed

    private void cboChucVuItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboChucVuItemStateChanged
        // TODO add your handling code here:
//        String cv = (String) cboChucVu.getSelectedItem();
//        switch (cv) {
//            case "Bác sĩ":
//                txtMaNV.setText("bsi");
//                break;
////            case "Thu Ngân":
////                txtMaNV.setText("thng");
////                break;
//            case "Y tá":
//                txtMaNV.setText("yta");
//                break;
//            default:
//                throw new AssertionError();
//        }
    }//GEN-LAST:event_cboChucVuItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser JDCNgaySinh;
    private com.toedter.calendar.JDateChooser JDCNgayVL;
    private javax.swing.JPanel NhanVien;
    private javax.swing.JPanel ThongTinBS;
    private javax.swing.JButton btnChonAnh;
    private javax.swing.JButton btnMoi;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cboChucVu;
    private javax.swing.JComboBox<String> cboChuyenNganh;
    private javax.swing.JComboBox<String> cboTrinhDo;
    private javax.swing.JFileChooser fileChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAnhNV;
    private javax.swing.JRadioButton rdoNam;
    private javax.swing.JRadioButton rdoNu;
    public javax.swing.JTable tblDanhSachNV;
    private javax.swing.JPanel tblbangbacsy;
    private javax.swing.JTextField txtCMND;
    private javax.swing.JTextArea txtDiaChi;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtHoTenNV;
    private javax.swing.JTextField txtMaKhoa;
    private javax.swing.JTextField txtMaNV;
    private javax.swing.JTextField txtMaPhong;
    private javax.swing.JTextField txtSDT;
    public javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables

    NhanVienDao dao = new NhanVienDao();
    int row = -1;

    void init() {
        initTable();
        this.fillTable();
        this.row = -1;
        this.initcombobox();
        
    }
    public void initcombobox(){ 
        String[] ChuyenNganhString = {"Khoa Nội soi", "Khoa Nhi","Khoa Ngoại", "Khoa xét nghiệm", "Khoa Nội", "Khoa Chuẩn đoán hình ảnh","Khoa Dinh Dưỡng","Khoa Phụ sản","Khoa Truyền Nhiễm", "Khoa Dược"};
        model = (DefaultComboBoxModel) cboChuyenNganh.getModel();
        model.removeAllElements();
        for (int i = 0; i < ChuyenNganhString.length; i++) {
            model.addElement(ChuyenNganhString[i]);
        }
        
        String[] TrinhDoString = {"Đại học", "Cao Đẳng", "Cử nhân khoa học y tế", "Tiến sĩ y khoa","Cử nhân"};
         model = (DefaultComboBoxModel) cboTrinhDo.getModel();
        model.removeAllElements();
        for (int i = 0; i < TrinhDoString.length; i++) {
            model.addElement(TrinhDoString[i]);
        }

        String[] ChucVuString = {"Bác sĩ", "Thu Ngân", "Y tá"};
        model = (DefaultComboBoxModel) cboChucVu.getModel();
        model.removeAllElements();
        for (int i = 0; i < ChucVuString.length; i++) {
            model.addElement(ChucVuString[i]);
        }
    } 
    
    public void initTable() {
        DefaultTableModel model = (DefaultTableModel) tblDanhSachNV.getModel();
        model.setColumnIdentifiers(new String[]{"MaNV", "HotenNV", "GioiTinh", "NgaySinh", "DiaChi", "Email", "CMND", "ChuyenNganh", "ChucVu", "TrinhDo", "HinhAnhNV", "NgayVaoLam", "MaKhoa", "SDT","MaPhong"});
    }

    public void fillTable() {
        DefaultTableModel model = (DefaultTableModel) tblDanhSachNV.getModel();
        model.setRowCount(0);

        try {
            String keyword = txtTimKiem.getText();
            List<NhanVienPK> list = dao.selectByKeyword(keyword);
            for (NhanVienPK nv : list) {
                Object[] row = {
                    nv.getMaNV(),
                    nv.getHoTenNV(),
                    nv.getGioiTinh() ? "Nam" : "Nữ",
                    XDate.toString(nv.getNgaySinh(), "MM/dd/yyyy"),
                    nv.getDiaChi(),
                    nv.getEmail(),
                    nv.getCMND(),
                    nv.getChuyenNganh(),
                    nv.getChucVu(),
                    nv.getTrinhDo(),
                    nv.getHinhAnhNV(),
                    XDate.toString(nv.getNgayVaoLam(), "MM/dd/yyyy"),
                    nv.getMaKhoa(),
                    nv.getSDT(),
                    nv.getMaPhong()
                        ,};
                model.addRow(row);
            }
        } catch (Exception e) {
            MsgBox.alert(this, "Lỗi truy vấn dữ liệu!");
        }
    }

    void setForm(NhanVienPK nv) {
        txtMaNV.setText(nv.getMaNV());
        txtHoTenNV.setText(nv.getHoTenNV());
        if (nv.getGioiTinh()) {
            rdoNam.setSelected(true);
        } else {
            rdoNu.setSelected(true);
        }
        JDCNgaySinh.setDate(nv.getNgaySinh());       
        txtDiaChi.setText(nv.getDiaChi());
        txtEmail.setText(nv.getEmail());
        txtCMND.setText(nv.getCMND());
        cboChuyenNganh.setSelectedItem((Object) nv.getChuyenNganh());
        cboTrinhDo.setSelectedItem((Object) nv.getTrinhDo());
        cboChucVu.setSelectedItem((Object) nv.getChucVu());
        if (nv.getHinhAnhNV() != null) {
            lblAnhNV.setToolTipText(nv.getHinhAnhNV());
            lblAnhNV.setIcon(XImage.read(nv.getHinhAnhNV()));
        }
        JDCNgayVL.setDate(nv.getNgayVaoLam());  
        txtMaKhoa.setText(nv.getMaKhoa());
        txtSDT.setText(nv.getSDT());
        txtMaPhong.setText(nv.getMaPhong());

    }

    void clearForm() {
        NhanVienPK nv = new NhanVienPK();
        this.setForm(nv);
        this.row = -1;
    }

    NhanVienPK getForm() {
        NhanVienPK nv = new NhanVienPK();
        nv.setMaNV(txtMaNV.getText());
        nv.setHoTenNV(txtHoTenNV.getText());
        nv.setGioiTinh(rdoNam.isSelected());
        nv.setNgaySinh(JDCNgaySinh.getDate());
        nv.setDiaChi(txtDiaChi.getText());
        nv.setEmail(txtEmail.getText());
        nv.setCMND(txtCMND.getText());
        nv.setChuyenNganh(cboChuyenNganh.getSelectedItem().toString());
        nv.setTrinhDo(cboTrinhDo.getSelectedItem().toString());
        nv.setChucVu(cboChucVu.getSelectedItem().toString());
        nv.setHinhAnhNV(lblAnhNV.getToolTipText());
        nv.setNgayVaoLam(JDCNgayVL.getDate());
        nv.setMaKhoa(txtMaKhoa.getText());
        nv.setSDT(txtSDT.getText());
        nv.setMaPhong(txtMaPhong.getText());
        return nv;
    }

    void insert() {
        NhanVienPK nv = this.getForm();
        try {
            dao.insert(nv);
            this.fillTable();
            this.clearForm();
            MsgBox.alert(this, "thêm mới thành công");
        } catch (Exception e) {
            e.printStackTrace();    
            MsgBox.alert(this, "thêm mới Thất Bại");
        }
    }

    void edit() {
        String manv = (String) tblDanhSachNV.getValueAt(this.row, 0);
        NhanVienPK nv = dao.selectById(manv);
        this.setForm(nv);
//        NhanVien.setSelectedIndex(0);

    }

    void delete() {
        String manv = txtMaNV.getText();
        try {
            dao.delete(manv);
            this.fillTable();
            this.clearForm();
            MsgBox.alert(this, "Xóa thành công!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
            MsgBox.alert(this, "Xóa thất bại!");
        }
    }

    void update() {
        NhanVienPK model = getForm();
        try {
            dao.update(model);
            this.fillTable();
            MsgBox.alert(this, "Cập nhật thành công!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
            MsgBox.alert(this, "Cập nhật thất bại!");
        }
    }
//    private void timKiem() {
//        this.fillTable();
//        this.clearForm();
//        this.row = -1;
////        this.updateStatus();
//    }
    void chonAnh() {
        JFileChooser fileChooser = new JFileChooser("D:\\QLDA1_T_Phung\\QL_PhongKham\\src\\PhongKham\\Hinh\\anhbs");
        if (fileChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();
            XImage.save(file); // lưu hình vào thư mục logos
            ImageIcon icon = XImage.read(file.getName()); // đọc hình từ logos
            lblAnhNV.setIcon(icon);
            lblAnhNV.setToolTipText(file.getName()); // giữ tên hình trong tooltip
        }
    }
    
    
     boolean isValidated(){
        
           // kiểm tra MaNV
        if(txtMaNV.getText().trim().length() == 0){
            // 1.thông báo lỗi 
            JOptionPane.showMessageDialog(this, "Mã Nhân Viên không được để trống !");
            // 2. set màu
            txtMaNV.setBackground(Color.YELLOW);
            // 3. sét nháy
            txtMaNV.requestFocus();
            // 4. kết thúc hàm ko làm các lệnh phía sau
            return false; 
        }else{
            txtMaNV.setBackground(Color.white);
        }
        
        // ********************************************************************** // 
        
           // kiểm tra HoTenNV
        if(txtHoTenNV.getText().trim().length() == 0){
            // 1.thông báo lỗi 
            JOptionPane.showMessageDialog(this, "Họ Tên Nhân Viên không được để trống !");
            // 2. set màu
            txtHoTenNV.setBackground(Color.YELLOW);
            // 3. sét nháy
            txtHoTenNV.requestFocus();
            // 4. kết thúc hàm ko làm các lệnh phía sau
            return false; 
        }else{
            txtHoTenNV.setBackground(Color.white);
        }
        
        // ********************************************************************** // 
        
          // kiểm tra giới tính
        if(!(rdoNam.isSelected()) && !(rdoNu.isSelected())){
            JOptionPane.showMessageDialog(this,"Chọn giới tính !");
             return false;  
        }
        
        // ********************************************************************** // 
        
           // kiểm tra NgaySinh
        if(JDCNgaySinh.getDate() == null){
            // 1.thông báo lỗi 
            JOptionPane.showMessageDialog(this, "Ngày Sinh không được để trống !");
            return false;
        }
        
        // ********************************************************************** // 
        
           // kiểm tra Địa Chỉ
        if(txtDiaChi.getText().trim().length() == 0){
            // 1.thông báo lỗi 
            JOptionPane.showMessageDialog(this, "Địa Chỉ không được để trống !");
            // 2. set màu
            txtDiaChi.setBackground(Color.YELLOW);
            // 3. sét nháy
            txtDiaChi.requestFocus();
            // 4. kết thúc hàm ko làm các lệnh phía sau
            return false; 
        }else{
            txtDiaChi.setBackground(Color.white);
        }
        
        // ********************************************************************** // 
          // kiểm tra Email
        if(txtEmail.getText().trim().length() == 0){
            // 1.thông báo lỗi 
            JOptionPane.showMessageDialog(this, "Email không được để trống !");
            // 2. set màu
            txtEmail.setBackground(Color.YELLOW);
            // 3. sét nháy
            txtEmail.requestFocus();
            // 4. kết thúc hàm ko làm các lệnh phía sau
            return false; 
        }else{
            txtEmail.setBackground(Color.white);
        }
        
             // nhập đúng định dạng email
        Matcher matcher = Pattern.compile(Email).matcher(txtEmail.getText());
        if(!matcher.matches()){
            // 2 thông báo 
            JOptionPane.showMessageDialog(this,"Email sai định dạng?");
            // 3 set màu nền 
            txtEmail.setBackground(Color.yellow);
            // 4 set con nháy lằm tại đó 
            txtEmail.requestFocus();    
            return false; // 5 kết thúc hàm ko làm các lệnh phía sau 
           
        }
        
        // ********************************************************************** // 
           // kiểm tra CMND
        
          try {
            double CMND = Double.parseDouble(txtCMND.getText());
            
            if(CMND < 0 || CMND > 12){
                // 1.thông báo lỗi 
                JOptionPane.showMessageDialog(this, "CMND phải nằm trong khoảng từ 0 --> 12 !");
                // 2. set màu
                txtCMND.setBackground(Color.YELLOW);
                // 3. sét nháy
                txtCMND.requestFocus();
                // 4. kết thúc hàm ko làm các lệnh phía sau
                return false; 
            }else{
                 txtCMND.setBackground(Color.WHITE);
            }
        } catch (Exception e) {
            // 1.thông báo lỗi 
            JOptionPane.showMessageDialog(this, "CMND phải là số !");
            // 2. set màu
            txtCMND.setBackground(Color.YELLOW);
            // 3. sét nháy
            txtCMND.setText("");
            txtCMND.requestFocus();
            // 4. kết thúc hàm ko làm các lệnh phía sau
            return false; 
        }
        
        // ********************************************************************** // 
           // kiểm tra Chuyên Ngành
//        if(nv.getChuyenNganh().trim().length() != ChuyenNganhString){
//            // 1.thông báo lỗi 
//            JOptionPane.showMessageDialog(this, "Mã Nhân Viên không được để trống !");
//            // 2. set màu
//            cboChuyenNganh.setBackground(Color.YELLOW);
//            // 3. sét nháy
//            txtMaNV.requestFocus();
//            // 4. kết thúc hàm ko làm các lệnh phía sau
//            return false; 
//        }else{
//            txtMaNV.setBackground(Color.white);
//        }
        
        // ********************************************************************** // 
//           // kiểm tra chucvu
//        if(txtMaNV.getText().trim().length() == 0){
//            // 1.thông báo lỗi 
//            JOptionPane.showMessageDialog(this, "Mã Nhân Viên không được để trống !");
//            // 2. set màu
//            txtMaNV.setBackground(Color.YELLOW);
//            // 3. sét nháy
//            txtMaNV.requestFocus();
//            // 4. kết thúc hàm ko làm các lệnh phía sau
//            return false; 
//        }else{
//            txtMaNV.setBackground(Color.white);
//        }
//        
        // ********************************************************************** // 
//           // kiểm tra trinh do
//        if(txtMaNV.getText().trim().length() == 0){
//            // 1.thông báo lỗi 
//            JOptionPane.showMessageDialog(this, "Mã Nhân Viên không được để trống !");
//            // 2. set màu
//            txtMaNV.setBackground(Color.YELLOW);
//            // 3. sét nháy
//            txtMaNV.requestFocus();
//            // 4. kết thúc hàm ko làm các lệnh phía sau
//            return false; 
//        }else{
//            txtMaNV.setBackground(Color.white);
//        }
        
        // ********************************************************************** // 
           // kiểm tra HinhAnhNV
//        if(nv.getHinhAnhNV() == null){
//            // 1.thông báo lỗi 
//            JOptionPane.showMessageDialog(this, "Hình ảnh Chưa Có không được để trống !");
//            // 2. set màu
//            lblAnhNV.setBackground(Color.YELLOW);
//            // 3. sét nháy
//            lblAnhNV.requestFocus();
//            // 4. kết thúc hàm ko làm các lệnh phía sau
//            return false; 
//        }else{
//            lblAnhNV.setBackground(Color.white);
//        }
        
        // ********************************************************************** // 
           // kiểm tra NgayVL
        if(JDCNgayVL.getDate() == null){
            // 1.thông báo lỗi 
            JOptionPane.showMessageDialog(this, "Ngày VL không được để trống !");           
            return false; 
        }
        
        // ********************************************************************** // 
           // kiểm tra Mã Khoa
        if(txtMaKhoa.getText().trim().length() == 0){
            // 1.thông báo lỗi 
            JOptionPane.showMessageDialog(this, "Mã khoa không được để trống !");
            // 2. set màu
            txtMaKhoa.setBackground(Color.YELLOW);
            // 3. sét nháy
            txtMaKhoa.requestFocus();
            // 4. kết thúc hàm ko làm các lệnh phía sau
            return false; 
        }else{
            txtMaKhoa.setBackground(Color.white);
        }
        
        // ********************************************************************** // 
           // kiểm tra SDT           
        Matcher matchersdt = Pattern.compile(phonePattern).matcher(txtSDT.getText());
        if (txtSDT.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(this, "Số Điện Thoại Không Được Để Trống", "ERROR", JOptionPane.ERROR_MESSAGE);
            txtSDT.setBackground(Color.YELLOW);
            txtSDT.requestFocus();
            txtSDT.setText("");
            return false;
        } else {
            if (!matchersdt.matches()) {
                JOptionPane.showMessageDialog(this, "Số Điện Thoại Sai Định Dạng", "ERROR", JOptionPane.ERROR_MESSAGE);
                txtSDT.setBackground(Color.YELLOW);
                txtSDT.requestFocus();
                txtSDT.setText("");
                return false;
            } else {
                txtSDT.setBackground(Color.white);
            }
        }
           
        
        return true;
    } 
}
