/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PhongKham.ui;

import PhongKham.dao.ThietBiDao;
import PhongKham.dao.ThongKePKDao;
import PhongKham.entity.ThietBiPK;
import PhongKham.utils.XJdbc;
import java.awt.print.PrinterException;
import java.text.MessageFormat;
import java.util.Hashtable;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Admin
 */
public class ThongKeTB extends javax.swing.JPanel {

    /**
     * Creates new form ThongKeTB
     */
    String path = null;
    public ThongKeTB() {
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblThongKeTB = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblThongKeTBNV = new javax.swing.JTable();
        cboThang = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cboThang1 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnPDF = new javax.swing.JButton();
        in = new javax.swing.JButton();

        setBackground(new java.awt.Color(93, 167, 219));
        setPreferredSize(new java.awt.Dimension(1600, 900));

        tblThongKeTB.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Loại", "Tên Loại", "Số Lượng"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblThongKeTB.setRowHeight(30);
        tblThongKeTB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblThongKeTBMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblThongKeTB);

        tblThongKeTBNV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã thiết bị", "Tên thiế bị", "Ngày Nhập", "Tên loại thiết bị"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblThongKeTBNV.setRowHeight(30);
        jScrollPane2.setViewportView(tblThongKeTBNV);

        cboThang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tháng", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        cboThang.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboThangItemStateChanged(evt);
            }
        });
        cboThang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboThangActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Tháng");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Năm");

        cboThang1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Năm", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", " " }));
        cboThang1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboThang1ItemStateChanged(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("THỐNG KÊ THIẾT BỊ PHÒNG KHÁM");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("29/11/2022");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(503, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(412, 412, 412))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(621, 621, 621))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PhongKham/Hinh/excel.png"))); // NOI18N
        jButton1.setText("Xuất file Execl");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnPDF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PhongKham/Hinh/pdf.png"))); // NOI18N
        btnPDF.setText("Xuất file PDF");
        btnPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPDFActionPerformed(evt);
            }
        });

        in.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PhongKham/Hinh/printer.png"))); // NOI18N
        in.setText("IN");
        in.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 728, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane2)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(18, 18, 18)
                                        .addComponent(cboThang, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(49, 49, 49)
                                        .addComponent(jLabel2)
                                        .addGap(28, 28, 28)
                                        .addComponent(cboThang1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(234, 234, 234)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addComponent(btnPDF, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(in, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(87, 87, 87))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(91, 91, 91))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cboThang, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cboThang1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPDF, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(in, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(979, 979, 979))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblThongKeTBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblThongKeTBMouseClicked
        // TODO add your handling code here:
        int row = tblThongKeTB.getSelectedRow();
        String data = (String) tblThongKeTB.getValueAt(row, 0);
        System.out.println(data);
        this.fillTableThongKeSoLuongTBNV(data);
    }//GEN-LAST:event_tblThongKeTBMouseClicked

    private void inActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inActionPerformed
        // TODO add your handling code here:
         Hashtable map = new Hashtable();
        map.put("manv", "Yta01");
        map.put("tennv", "Nguyen Thanh Ha");
        map.put("gioitinh", "Nữ");
        map.put("chucvu", "Y tá");
         if (cboThang.getSelectedIndex() != 0 && cboThang1.getSelectedIndex() != 0) {
                path = "src/report/ThongKethieibitheothangnam.jrxml";
                map.put("Thang", Integer.parseInt((String) cboThang.getSelectedItem()));
                map.put("Nam", Integer.parseInt((String) cboThang1.getSelectedItem()));
                   
            } else if (cboThang1.getSelectedIndex() != 0) {
                path = "src/report/ThongKeThietBi_theonam.jrxml";
                map.put("nam", Integer.parseInt((String) cboThang1.getSelectedItem()));
                  
            } else {
                path = "src/report/ThongKeThietBi.jrxml";
                   
            }
            System.out.println("in pat tại 244  : "+ path);
           JasperReport jas;
            try {
                jas = JasperCompileManager.compileReport(path);
                JasperPrint print = JasperFillManager.fillReport(jas, map, XJdbc.consql());
                JasperViewer.viewReport(print, false);
            } catch (JRException ex) {
                System.out.println("lỗi report 249 " + ex);
            }

    }//GEN-LAST:event_inActionPerformed

    private void cboThangItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboThangItemStateChanged
        // TODO add your handling code here:
        
            select();
        
        
    }//GEN-LAST:event_cboThangItemStateChanged

    private void cboThang1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboThang1ItemStateChanged
        // TODO add your handling code here:
        
            select();
        
    }//GEN-LAST:event_cboThang1ItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPDFActionPerformed
        // TODO add your handling code here:
         try {
            String thongtin;

            thongtin = "Danh Sách Thống Kê Thiết Bị";

            MessageFormat header = new MessageFormat(thongtin);
            MessageFormat footer = new MessageFormat("1");           
            tblThongKeTB.print(JTable.PrintMode.NORMAL, header, footer);
        } catch (PrinterException ex) {
            Logger.getLogger(DichVuGD.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnPDFActionPerformed

    private void cboThangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboThangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboThangActionPerformed
    public void select() {
        tblThongKeTB.clearSelection();
        if (cboThang.getSelectedIndex() != 0 && cboThang1.getSelectedIndex() != 0) {
            DefaultTableModel model = (DefaultTableModel) tblThongKeTBNV.getModel();
            model.setRowCount(0);
            List<Object[]> list = dao.getSoLuongTBtheothangnam((String) cboThang.getSelectedItem(), (String) cboThang1.getSelectedItem());
            for (Object[] row : list) {
                model.addRow(row);
            }
        } else if (cboThang1.getSelectedIndex() != 0) {
            DefaultTableModel model = (DefaultTableModel) tblThongKeTBNV.getModel();
            model.setRowCount(0);
            List<Object[]> list = dao.getSoLuongTBtheonam((String) cboThang1.getSelectedItem());
            for (Object[] row : list) {
                model.addRow(row);
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPDF;
    private javax.swing.JComboBox<String> cboThang;
    private javax.swing.JComboBox<String> cboThang1;
    private javax.swing.JButton in;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblThongKeTB;
    private javax.swing.JTable tblThongKeTBNV;
    // End of variables declaration//GEN-END:variables
     ThongKePKDao dao = new ThongKePKDao();
    ThietBiDao daodao = new ThietBiDao();

    private void init() {
//        this.fillComboBoxThang();
        this.fillTableThongKeSoLuongTB();
//        fillTableThongKeSoLuongTBNV();
    }

    void fillComboBoxThang() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) cboThang.getModel();
        model.removeAllElements();
        List<Integer> list = daodao.selectMonth();
        for (Integer year : list) {
            model.addElement(year);
        }
    }

    void fillTableThongKeSoLuongTB() {
        DefaultTableModel model = (DefaultTableModel) tblThongKeTB.getModel();
        model.setRowCount(0);
        List<Object[]> list = dao.getSoLuongTB();
        for (Object[] row : list) {
            model.addRow(row);
        }
    }

    void fillTableThongKeSoLuongTBNV(String x) {
        DefaultTableModel model = (DefaultTableModel) tblThongKeTBNV.getModel();
        model.setRowCount(0);
        // int thang = (Integer)cboThang.getSelectedItem();
        List<Object[]> list = dao.getSoLuongTBNV(x);
        for (Object[] row : list) {
            model.addRow(row);
        }
    }
    
    void filltableThietBi(){
        DefaultTableModel model = (DefaultTableModel) tblThongKeTBNV.getModel();
        model.setRowCount(0);
        List<Object[]> list = dao.getSoLuongTB();
        for(Object[] row : list){
            model.addRow(row);
        }
    }

}
