/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PhongKham.ui;

import PhongKham.dao.ThongKePKDao;
import PhongKham.utils.MsgBox;
import PhongKham.utils.XJdbc;
import java.awt.print.PrinterException;
import java.text.MessageFormat;
import java.util.Hashtable;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Admin
 */
public class ThongKeThuoc extends javax.swing.JPanel {

    /**
     * Creates new form ThongKeThuoc
     */
    String path = null;

    public ThongKeThuoc() {

        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblThongKeT = new javax.swing.JTable();
        trangthai = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        thang = new javax.swing.JComboBox<>();
        nam = new javax.swing.JComboBox<>();
        tbnPDF = new javax.swing.JButton();
        tbnPDF1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(93, 167, 219));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        setPreferredSize(new java.awt.Dimension(1600, 900));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("THỐNG KÊ THUÔC PHÒNG KHÁM ĐA KHOA ");

        jLabel2.setText("30/11/2022");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(608, 608, 608))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 922, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(235, 235, 235))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        tblThongKeT.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        tblThongKeT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblThongKeT.setRowHeight(30);
        jScrollPane1.setViewportView(tblThongKeT);

        trangthai.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        trangthai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Đã bán", "Còn lại" }));
        trangthai.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                trangthaiItemStateChanged(evt);
            }
        });
        trangthai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trangthaiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(trangthai, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 986, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(188, Short.MAX_VALUE)
                .addComponent(trangthai, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(171, 171, 171))
        );

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PhongKham/Hinh/printer.png"))); // NOI18N
        jButton1.setText("In");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        thang.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        thang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tháng", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        thang.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                thangItemStateChanged(evt);
            }
        });
        thang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thangActionPerformed(evt);
            }
        });

        nam.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        nam.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Năm", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", " " }));
        nam.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                namItemStateChanged(evt);
            }
        });

        tbnPDF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PhongKham/Hinh/pdf.png"))); // NOI18N
        tbnPDF.setText("Xuất file PDF");
        tbnPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbnPDFActionPerformed(evt);
            }
        });

        tbnPDF1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PhongKham/Hinh/excel.png"))); // NOI18N
        tbnPDF1.setText("Xuất file PDF");
        tbnPDF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbnPDF1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(653, 653, 653)
                .addComponent(thang, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(123, 123, 123)
                .addComponent(nam, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tbnPDF1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68)
                        .addComponent(tbnPDF, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 54, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(thang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tbnPDF, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tbnPDF1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(235, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void trangthaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trangthaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_trangthaiActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.out.println(path);
        Hashtable map = new Hashtable();
        map.put("manv", "Yta01");
        map.put("tennv", "Nguyen Thanh Ha");
        map.put("gioitinh", "Nữ");
        map.put("chucvu", "Y tá");
        if (trangthai.getSelectedIndex() == 0) {
            if (thang.getSelectedIndex() != 0 && nam.getSelectedIndex() != 0) {
                path = "src/report/ThongKeThuoc_daban.jrxml";
                map.put("Thang", Integer.parseInt((String) thang.getSelectedItem()));
                map.put("Nam", Integer.parseInt((String) nam.getSelectedItem()));
                   
            } else if (nam.getSelectedIndex() != 0) {
                path = "src/report/ThongKeThuoc_daban_theonam.jrxml";
                map.put("nam", Integer.parseInt((String) nam.getSelectedItem()));
                  
            } else {
                path = "src/report/ThongKeThuoc_daban_all.jrxml";
                   
            }
            System.out.println("in pat tại 244  : "+ path);
           JasperReport jas;
            try {
                jas = JasperCompileManager.compileReport(path);
                JasperPrint print = JasperFillManager.fillReport(jas, map, XJdbc.consql());
                JasperViewer.viewReport(print, false);
            } catch (JRException ex) {
                System.out.println("lỗi report 249 " + ex);
            }
        } else {
            JasperReport jas;
            try {
                jas = JasperCompileManager.compileReport(path);
                JasperPrint print = JasperFillManager.fillReport(jas, map, XJdbc.consql());
                JasperViewer.viewReport(print, false);
            } catch (JRException ex) {
                System.out.println("lỗi report 259 " + ex);
            }

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void thangItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_thangItemStateChanged
        // TODO add your handling code here:
        if (thang.getSelectedIndex() != 0 && nam.getSelectedIndex() != 0) {
            filltablethuocdabantheothang();
        }else{
            filltableThuoc();
        }
    }//GEN-LAST:event_thangItemStateChanged

    private void namItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_namItemStateChanged
        // TODO add your handling code here:
        if (nam.getSelectedIndex() != 0 && thang.getSelectedIndex() != 0) {
            filltablethuocdabantheothang();
        } else if(nam.getSelectedIndex() != 0) {
            filltablethuocdabantheonam();
        }else{
            filltableThuoc();
        }

    }//GEN-LAST:event_namItemStateChanged
    public void filltablethuoconlai() {
        DefaultTableModel model = (DefaultTableModel) tblThongKeT.getModel();
        String header1[] = {"Mã thuốc", "Tên thuốc", "Số lượng", "Đơn vị"};
        model.setColumnIdentifiers(header1);
        model.setRowCount(0);
        List<Object[]> list = daotk.getLuongThuocConLai();
        for (Object[] objects : list) {
            model.addRow(objects);
        }
        tblThongKeT.setModel(model);
    }
    private void trangthaiItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_trangthaiItemStateChanged
        // TODO add your handling code here:
        if (trangthai.getSelectedIndex() == 0) {
            filltablethuocdaban();
            path = "src/report/ThongKeThuoc_daban_all.jrxml";
            thang.setEditable(true);
            nam.setEditable(true);
        } else {
            filltablethuoconlai();
            path = "src/report/ThongKeThuoc_conlai.jrxml";
            thang.setSelectedIndex(0);
            nam.setSelectedIndex(0);
            thang.setEditable(false);
            nam.setEditable(false);
        }
    }//GEN-LAST:event_trangthaiItemStateChanged

    private void thangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_thangActionPerformed

    private void tbnPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbnPDFActionPerformed
        // TODO add your handling code here:
         try {
            String thongtin;

            thongtin = "Danh Sách Thống Kê Thuốc";

            MessageFormat header = new MessageFormat(thongtin);
            MessageFormat footer = new MessageFormat("1");           
            tblThongKeT.print(JTable.PrintMode.NORMAL, header, footer);
        } catch (PrinterException ex) {
            Logger.getLogger(DichVuGD.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tbnPDFActionPerformed

    private void tbnPDF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbnPDF1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbnPDF1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> nam;
    private javax.swing.JTable tblThongKeT;
    private javax.swing.JButton tbnPDF;
    private javax.swing.JButton tbnPDF1;
    private javax.swing.JComboBox<String> thang;
    private javax.swing.JComboBox<String> trangthai;
    // End of variables declaration//GEN-END:variables
    ThongKePKDao daotk = new ThongKePKDao();

    private void init() {
        System.out.println("chaybangcom");
        filltablethuocdaban();
    }

    String header[] = {"Mã thuốc", "Tên thuốc", "Số lượng ", "Ngày bán"};

    public void filltablethuocdabantheothang() {
        try {
            DefaultTableModel model = (DefaultTableModel) tblThongKeT.getModel();
            String thangban = (String) thang.getSelectedItem();
            String namban = (String) nam.getSelectedItem();
            model.setColumnIdentifiers(header);
            model.setRowCount(0);
            List<Object[]> list = daotk.getSoLuongThuocDB(thangban, namban);
            for (Object[] objects : list) {
                model.addRow(objects);
            }
            tblThongKeT.setModel(model);
        } catch (Exception e) {
        }

    }

    public void filltablethuocdabantheonam() {
        DefaultTableModel model = (DefaultTableModel) tblThongKeT.getModel();
        String namban = (String) nam.getSelectedItem();
        model.setColumnIdentifiers(header);
        model.setRowCount(0);
        List<Object[]> list = daotk.getSLThuocTheonam(namban);
        for (Object[] objects : list) {
            model.addRow(objects);
        }
        tblThongKeT.setModel(model);
    }

    public void filltablethuocdaban() {
        DefaultTableModel model = (DefaultTableModel) tblThongKeT.getModel();
        model.setColumnIdentifiers(header);
        System.out.println("1");
        model.setRowCount(0);
        List<Object[]> list = daotk.getSoLuongThuocDB_khongtheothang();
        for (Object[] objects : list) {
            model.addRow(objects);
        }
        tblThongKeT.setModel(model);
    }

    void filltableThuoc(){
        DefaultTableModel model = (DefaultTableModel) tblThongKeT.getModel();
        model.setRowCount(0);
        List<Object[]> list = daotk.getSoLuongThuocDB_khongtheothang();
        for(Object[] row : list){
            model.addRow(row);
        }
    }
    
}
