/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PhongKham.ui;

import PhongKham.dao.ThuocDao;
import PhongKham.entity.ThuocPK;
import PhongKham.utils.MsgBox;
import PhongKham.utils.XDate;
import java.awt.Color;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class ThuocGD extends javax.swing.JPanel {
    DefaultComboBoxModel model;
    /**
     * Creates new form Thuoc
     */
    public ThuocGD() {
        initComponents();
        init();
        
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ThongTinThuoc = new javax.swing.JPanel();
        txtMaThuoc = new javax.swing.JTextField();
        txtDonGia = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtMaNV = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtSoLuong = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        btnMoi = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        JDCNgayNhap = new com.toedter.calendar.JDateChooser();
        JDCHSD = new com.toedter.calendar.JDateChooser();
        JDCNgaySX = new com.toedter.calendar.JDateChooser();
        cboDonVi = new javax.swing.JComboBox<>();
        cboTenThuoc = new combo_suggestion.ComboBoxSuggestion();
        jLabel13 = new javax.swing.JLabel();
        cboCachDung = new combo_suggestion.ComboBoxSuggestion();
        cboLoaiThuoc = new combo_suggestion.ComboBoxSuggestion();
        DSThuoc = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDanhSachThuoc = new javax.swing.JTable();
        TKThuoc = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtTimKiem = new javax.swing.JTextField();

        setBackground(new java.awt.Color(93, 167, 219));
        setPreferredSize(new java.awt.Dimension(1553, 900));

        ThongTinThuoc.setBackground(new java.awt.Color(129, 198, 232));
        ThongTinThuoc.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông Tin Thuốc", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 18))); // NOI18N

        txtMaThuoc.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtMaThuoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaThuocActionPerformed(evt);
            }
        });

        txtDonGia.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtDonGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDonGiaActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Mã NV");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Tên thuốc");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Đơn vị");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("HSD");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Ngày Nhập");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Loại Thuốc:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Đơn giá");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Mã Thuốc");

        txtMaNV.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtMaNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaNVActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Số Lượng");

        txtSoLuong.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtSoLuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSoLuongActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("NgàySX");

        btnMoi.setBackground(new java.awt.Color(125, 229, 237));
        btnMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PhongKham/Hinh/new.png"))); // NOI18N
        btnMoi.setText("Làm Mới");
        btnMoi.setBorder(null);
        btnMoi.setFocusable(false);
        btnMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoiActionPerformed(evt);
            }
        });

        btnXoa.setBackground(new java.awt.Color(125, 229, 237));
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PhongKham/Hinh/delete.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.setBorder(null);
        btnXoa.setFocusable(false);
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnSua.setBackground(new java.awt.Color(125, 229, 237));
        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PhongKham/Hinh/loop.png"))); // NOI18N
        btnSua.setText("Sửa");
        btnSua.setBorder(null);
        btnSua.setFocusable(false);
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnThem.setBackground(new java.awt.Color(125, 229, 237));
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PhongKham/Hinh/add-friend.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.setBorder(null);
        btnThem.setFocusable(false);
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        cboDonVi.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Cách Dùng");

        javax.swing.GroupLayout ThongTinThuocLayout = new javax.swing.GroupLayout(ThongTinThuoc);
        ThongTinThuoc.setLayout(ThongTinThuocLayout);
        ThongTinThuocLayout.setHorizontalGroup(
            ThongTinThuocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ThongTinThuocLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ThongTinThuocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ThongTinThuocLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtMaThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addGap(50, 50, 50)
                        .addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ThongTinThuocLayout.createSequentialGroup()
                        .addGroup(ThongTinThuocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4))
                        .addGap(35, 35, 35)
                        .addGroup(ThongTinThuocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ThongTinThuocLayout.createSequentialGroup()
                                .addComponent(cboDonVi, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel10)
                                .addGap(32, 32, 32)
                                .addComponent(txtSoLuong))
                            .addComponent(cboLoaiThuoc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(ThongTinThuocLayout.createSequentialGroup()
                                .addGroup(ThongTinThuocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(ThongTinThuocLayout.createSequentialGroup()
                                        .addComponent(txtDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel11))
                                    .addGroup(ThongTinThuocLayout.createSequentialGroup()
                                        .addComponent(JDCNgayNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel5)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(ThongTinThuocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(JDCNgaySX, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                                    .addComponent(JDCHSD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(ThongTinThuocLayout.createSequentialGroup()
                        .addGroup(ThongTinThuocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ThongTinThuocLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(48, 48, 48)
                                .addComponent(cboTenThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel13)
                                .addGap(26, 26, 26)
                                .addComponent(cboCachDung, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ThongTinThuocLayout.createSequentialGroup()
                                .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44)
                                .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49)
                                .addComponent(btnMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        ThongTinThuocLayout.setVerticalGroup(
            ThongTinThuocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ThongTinThuocLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(ThongTinThuocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(ThongTinThuocLayout.createSequentialGroup()
                        .addGroup(ThongTinThuocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(txtMaThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGroup(ThongTinThuocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ThongTinThuocLayout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addGroup(ThongTinThuocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(cboTenThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cboCachDung, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(31, 31, 31)
                                .addGroup(ThongTinThuocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addGroup(ThongTinThuocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(cboDonVi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(ThongTinThuocLayout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(jLabel13)
                                .addGap(46, 46, 46)
                                .addComponent(jLabel10)))
                        .addGap(44, 44, 44)
                        .addGroup(ThongTinThuocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(JDCNgayNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(JDCHSD, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(ThongTinThuocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel8)
                            .addComponent(txtDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JDCNgaySX, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11))
                        .addGap(27, 27, 27)
                        .addComponent(cboLoaiThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel7))
                .addGap(48, 48, 48)
                .addGroup(ThongTinThuocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        DSThuoc.setBackground(new java.awt.Color(129, 198, 232));
        DSThuoc.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh Sách Thuốc", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        tblDanhSachThuoc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã NV", "Mã Thuốc", "Thuốc", "Đơn Vị", "Số Lượng", "Ngày Sản Xuất", "Hạn Sử Dụng", "Đơn Giá", "Ngày Nhập", "Loại Thuốc", "Ghi Chú"
            }
        ));
        tblDanhSachThuoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDanhSachThuocMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblDanhSachThuocMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(tblDanhSachThuoc);

        javax.swing.GroupLayout DSThuocLayout = new javax.swing.GroupLayout(DSThuoc);
        DSThuoc.setLayout(DSThuocLayout);
        DSThuocLayout.setHorizontalGroup(
            DSThuocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DSThuocLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 849, Short.MAX_VALUE)
                .addContainerGap())
        );
        DSThuocLayout.setVerticalGroup(
            DSThuocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DSThuocLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );

        TKThuoc.setBackground(new java.awt.Color(129, 198, 232));
        TKThuoc.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tìm Kiếm Thuốc", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PhongKham/Hinh/search.png"))); // NOI18N
        jLabel1.setText("Find Name : ");

        txtTimKiem.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtTimKiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtTimKiemMouseClicked(evt);
            }
        });
        txtTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimKiemActionPerformed(evt);
            }
        });
        txtTimKiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTimKiemKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout TKThuocLayout = new javax.swing.GroupLayout(TKThuoc);
        TKThuoc.setLayout(TKThuocLayout);
        TKThuocLayout.setHorizontalGroup(
            TKThuocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TKThuocLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        TKThuocLayout.setVerticalGroup(
            TKThuocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TKThuocLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TKThuocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TKThuoc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ThongTinThuoc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DSThuoc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(DSThuoc, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(TKThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ThongTinThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(240, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtMaThuocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaThuocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaThuocActionPerformed

    private void txtDonGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDonGiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDonGiaActionPerformed

    private void txtMaNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaNVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaNVActionPerformed

    private void txtSoLuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSoLuongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSoLuongActionPerformed

    private void btnMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoiActionPerformed
        // TODO add your handling code here:
        this.clearForm();
    }//GEN-LAST:event_btnMoiActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        this.insert(); 
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        this.update();
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        this.delete();
    }//GEN-LAST:event_btnXoaActionPerformed

    private void tblDanhSachThuocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDanhSachThuocMouseClicked
        // TODO add your handling code here:
         if(evt.getClickCount() == 1){
            this.row = tblDanhSachThuoc.getSelectedRow();
            this.edit();
        }
             
    }//GEN-LAST:event_tblDanhSachThuocMouseClicked

    private void txtTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimKiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimKiemActionPerformed

    private void txtTimKiemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTimKiemMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtTimKiemMouseClicked

    private void txtTimKiemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimKiemKeyReleased
        // TODO add your handling code here:
        this.fillTable();
    }//GEN-LAST:event_txtTimKiemKeyReleased

    private void tblDanhSachThuocMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDanhSachThuocMousePressed
        // TODO add your handling code here:
        if(evt.getClickCount() == 2){
        String mabn = (String) tblDanhSachThuoc.getValueAt(this.row, 0);
        ThuocPK  tt = dao.selectById(mabn);
        this.setForm(tt);
            ThuocChiTiet t = new ThuocChiTiet(tt);
        t.setVisible(true);
        }
        
    }//GEN-LAST:event_tblDanhSachThuocMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DSThuoc;
    private com.toedter.calendar.JDateChooser JDCHSD;
    private com.toedter.calendar.JDateChooser JDCNgayNhap;
    private com.toedter.calendar.JDateChooser JDCNgaySX;
    private javax.swing.JPanel TKThuoc;
    private javax.swing.JPanel ThongTinThuoc;
    private javax.swing.JButton btnMoi;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private combo_suggestion.ComboBoxSuggestion cboCachDung;
    private javax.swing.JComboBox<String> cboDonVi;
    private combo_suggestion.ComboBoxSuggestion cboLoaiThuoc;
    private combo_suggestion.ComboBoxSuggestion cboTenThuoc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblDanhSachThuoc;
    private javax.swing.JTextField txtDonGia;
    private javax.swing.JTextField txtMaNV;
    private javax.swing.JTextField txtMaThuoc;
    private javax.swing.JTextField txtSoLuong;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
       ThuocDao dao = new ThuocDao();
    int row = -1 ;
    
    void init(){
//        setLocationRelativeTo(null);
        this.fillTable();
        this.initTable();
        this.initcombobox();
    }
    public void initcombobox(){ 
        this.setBackground(new Color(255, 255, 255));
        String[] tenthuoc = {"Amoxcillin","Aspirin","Ampicillin","Clopheniramin","Paracetamol","Men vi sinh","Aciclovir","Hidrasec","Smecta",
            "Aciclovir","Nước mắt nhân tạo Systane","Nacl 0,9%","Darktarin","Mouthpast","Salonpas","Dạ hương","Lactacyd","Dán con cọp","Biotin Collagen 30","Omega 3 Fish Oil – Softgels"};
        model = (DefaultComboBoxModel) cboTenThuoc.getModel();
        model.removeAllElements();
        for (int i = 0; i < tenthuoc.length; i++) {
            model.addElement(tenthuoc[i]);
        }
        
        String[] cachdung = {"Uống","nhỏ mắt","Bôi","Dán","Rửa"};
        model = (DefaultComboBoxModel) cboCachDung.getModel();
        model.removeAllElements();
        for (int i = 0; i < cachdung.length; i++) {
            model.addElement(cachdung[i]);
        }
        
        String[] donvi = {"Viên","Chai","Gói","Hộp","Tuýp","Vỉ"};
        model = (DefaultComboBoxModel) cboDonVi.getModel();
        model.removeAllElements();
        for (int i = 0; i < donvi.length; i++) {
            model.addElement(donvi[i]);
        }
        
        String[] loaithuoc = {"Giảm đau hạ sốt","Nhóm tiêu hóa","Kháng virus","Nhóm trị tiêu chảy","Nhóm giảm co thắt","Nhóm thuốc nhỏ mắt",
            "Nhóm thuốc bôi lỡ miệng","Nhóm dán – bôi giảm đau","Nhóm nước rửa phụ khoa","Nhóm thực phẩm chức năng"};
        model = (DefaultComboBoxModel) cboLoaiThuoc.getModel();
        model.removeAllElements();
        for (int i = 0; i < loaithuoc.length; i++) {
            model.addElement(loaithuoc[i]);
        }
    }
    public void initTable(){
        DefaultTableModel model = (DefaultTableModel) tblDanhSachThuoc.getModel();
        model.setColumnIdentifiers(new String[]{"MaThuoc","TenThuoc","CachDung","LoaiThuoc","SoLuong","DonVi","DonGia","NgayNhap","NgaySX","HSD","MaNV"});
    }

    void fillTable() {
        DefaultTableModel model = (DefaultTableModel) tblDanhSachThuoc.getModel();
        model.setRowCount(0);
        
        try {
            String keyword = txtTimKiem.getText();
            List<ThuocPK> list = dao.selectByKeyword(keyword);
            for(ThuocPK t : list){
                Object[] row = {
                   t.getMaThuoc(),
                   t.getTenThuoc(),
                   t.getCachDung(),
                   t.getLoaiThuoc(),
                   t.getSoLuong(),
                   t.getDonVi(),
                   t.getDonGia(),
                   XDate.toString(t.getNgayNhap(), "dd/MM/yyy"),
                   XDate.toString(t.getNgaySX(), "dd/MM/yyy"),
                   XDate.toString(t.getHSD(), "dd/MM/yyy"),
                   t.getMaNV(),
                   };
                model.addRow(row);             
            }
        } catch (Exception e) {
            MsgBox.alert(this, "Lỗi truy vấn dữ liệu!");
        }
    
    }
    
    void setForm(ThuocPK t){
        txtMaThuoc.setText(t.getMaThuoc());
        cboTenThuoc.setSelectedItem(t.getTenThuoc());           
        cboCachDung.setSelectedItem(t.getCachDung());       
        cboLoaiThuoc.setSelectedItem(t.getLoaiThuoc());   
        txtSoLuong.setText(String.valueOf(t.getSoLuong()));
        cboDonVi.setSelectedItem(t.getDonVi());   
        txtDonGia.setText(String.valueOf(t.getDonGia()));       
        JDCNgayNhap.setDate(t.getNgayNhap()); 
        JDCNgaySX.setDate(t.getNgaySX()); 
        JDCHSD.setDate(t.getHSD()); 
        txtMaNV.setText(t.getMaNV());    
    }
    
    void clearForm(){
        ThuocPK t = new ThuocPK();
        this.setForm(t);
        this.row=-1;
    }
    
    ThuocPK getForm() {
        ThuocPK t = new ThuocPK();
        t.setMaThuoc(txtMaThuoc.getText());
        t.setTenThuoc(cboTenThuoc.getSelectedItem().toString());
        t.setCachDung(cboCachDung.getSelectedItem().toString());
        t.setLoaiThuoc(cboLoaiThuoc.getSelectedItem().toString());
        t.setSoLuong(Integer.valueOf(txtSoLuong.getText()));
        t.setDonVi(cboDonVi.getSelectedItem().toString());
        t.setDonGia(Float.valueOf(txtDonGia.getText()));
        t.setNgayNhap(JDCNgayNhap.getDate());
        t.setNgaySX(JDCNgaySX.getDate());
        t.setHSD(JDCHSD.getDate());
        t.setMaNV(txtMaNV.getText());      
        return t;
    }
    
    
     void insert() {
        ThuocPK t = this.getForm();
        try {
            dao.insert(t);
            this.fillTable();
            this.clearForm();
            MsgBox.alert(this, "thêm mới thành công");
        } catch (Exception e) {
            MsgBox.alert(this, "thêm mới thành công");
        }
    }

    void edit() {
        String mat = (String) tblDanhSachThuoc.getValueAt(this.row, 0);
        ThuocPK t = dao.selectById(mat);
        this.setForm(t);
//        NhanVien.setSelectedIndex(0);

    }

    void delete() {
        String mat = txtMaThuoc.getText();
        try {
            dao.delete(mat);
            this.fillTable();
            this.clearForm();
            MsgBox.alert(this, "Xóa thành công!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
            MsgBox.alert(this, "Xóa thất bại!");
        }
    }

    void update() {
        ThuocPK model = getForm();
        try {
            dao.update(model);
            this.fillTable();
            MsgBox.alert(this, "Cập nhật thành công!");
        } catch (Exception e) {
             JOptionPane.showMessageDialog(this, e);
            MsgBox.alert(this, "Cập nhật thất bại!");
        }
    }
    
    private void timKiem() {
        this.fillTable();
        this.clearForm();
        this.row = -1;
//        this.updateStatus();
    }
}
